# Generated by Django 5.2.13 on 2026-04-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CanonicalPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reep_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="CanonicalTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reep_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_code", models.CharField(db_index=True, max_length=32)),
                ("country", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=32, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["-sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("understat_league", models.CharField(default="EPL", max_length=32)),
                (
                    "understat_season_year",
                    models.CharField(
                        help_text="Understat URL segment, e.g. 2025 for 2025-26 depending on Understat convention.",
                        max_length=8,
                    ),
                ),
                ("sofascore_unique_tournament_id", models.PositiveIntegerField()),
                ("sofascore_season_id", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="ingestion.competition",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_links",
                        to="ingestion.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reep_sync", "Reep sync"),
                            ("understat", "Understat"),
                            ("sofascore", "Sofascore"),
                            ("merge", "Merge"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                (
                    "competition_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_runs",
                        to="ingestion.competitionseason",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReepPlayerRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reep_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "understat_player_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "sofascore_player_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("understat_player_id__isnull", False)),
                        fields=("understat_player_id",),
                        name="uniq_reep_player_understat_id",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("sofascore_player_id__isnull", False)),
                        fields=("sofascore_player_id",),
                        name="uniq_reep_player_sofascore_id",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReepTeamRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reep_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "understat_team_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "sofascore_team_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("understat_team_id__isnull", False)),
                        fields=("understat_team_id",),
                        name="uniq_reep_team_understat_id",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("sofascore_team_id__isnull", False)),
                        fields=("sofascore_team_id",),
                        name="uniq_reep_team_sofascore_id",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SofascorePlayerSeasonSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_player_id", models.CharField(db_index=True, max_length=64)),
                (
                    "provider_team_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("player_name", models.CharField(blank=True, max_length=200)),
                ("team_name", models.CharField(blank=True, max_length=200)),
                ("position_raw", models.CharField(blank=True, max_length=64)),
                ("appearances", models.PositiveIntegerField(blank=True, null=True)),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("tackles", models.PositiveIntegerField(blank=True, null=True)),
                ("interceptions", models.PositiveIntegerField(blank=True, null=True)),
                ("clearances", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "error_lead_to_goal",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "outfielder_blocks",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("accurate_passes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "inaccurate_passes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_passes", models.PositiveIntegerField(blank=True, null=True)),
                ("key_passes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "accurate_crosses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "accurate_long_balls",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("saves", models.PositiveIntegerField(blank=True, null=True)),
                ("clean_sheet", models.PositiveIntegerField(blank=True, null=True)),
                ("penalty_save", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "canonical_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sofascore_sources",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "canonical_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sofascore_sources",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sofascore_sources",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sofascore_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnderstatPlayerSeasonSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_player_id", models.CharField(db_index=True, max_length=64)),
                (
                    "provider_team_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("player_name", models.CharField(blank=True, max_length=200)),
                ("team_name", models.CharField(blank=True, max_length=200)),
                ("position_raw", models.CharField(blank=True, max_length=64)),
                ("games", models.PositiveIntegerField(blank=True, null=True)),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("goals", models.PositiveIntegerField(blank=True, null=True)),
                ("assists", models.PositiveIntegerField(blank=True, null=True)),
                ("shots", models.PositiveIntegerField(blank=True, null=True)),
                ("key_passes", models.PositiveIntegerField(blank=True, null=True)),
                ("npg", models.PositiveIntegerField(blank=True, null=True)),
                ("xg", models.FloatField(blank=True, null=True)),
                ("npxg", models.FloatField(blank=True, null=True)),
                ("xa", models.FloatField(blank=True, null=True)),
                ("xgchain", models.FloatField(blank=True, null=True)),
                ("xgbuildup", models.FloatField(blank=True, null=True)),
                ("yellow_cards", models.PositiveIntegerField(blank=True, null=True)),
                ("red_cards", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "canonical_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="understat_sources",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "canonical_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="understat_sources",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="understat_sources",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="understat_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnmatchedProviderPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("understat", "Understat"),
                            ("sofascore", "Sofascore"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_player_id", models.CharField(db_index=True, max_length=64)),
                ("player_name", models.CharField(blank=True, max_length=200)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unmatched_players",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "first_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unmatched_players_introduced",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "resolved_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quarantine_resolutions",
                        to="ingestion.canonicalplayer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnmatchedProviderTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("understat", "Understat"),
                            ("sofascore", "Sofascore"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_team_id", models.CharField(db_index=True, max_length=64)),
                ("team_name", models.CharField(blank=True, max_length=200)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unmatched_teams",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "first_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unmatched_teams_introduced",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "resolved_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quarantine_team_resolutions",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MergedPlayerSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_group",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=8,
                    ),
                ),
                ("native_position", models.CharField(blank=True, max_length=64)),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metadata_authority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("understat", "Understat"),
                            ("sofascore", "Sofascore"),
                        ],
                        max_length=16,
                    ),
                ),
                ("us_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("us_assists", models.PositiveIntegerField(blank=True, null=True)),
                ("us_shots", models.PositiveIntegerField(blank=True, null=True)),
                ("us_key_passes", models.PositiveIntegerField(blank=True, null=True)),
                ("us_npg", models.PositiveIntegerField(blank=True, null=True)),
                ("us_xg", models.FloatField(blank=True, null=True)),
                ("us_npxg", models.FloatField(blank=True, null=True)),
                ("us_xa", models.FloatField(blank=True, null=True)),
                ("us_xgchain", models.FloatField(blank=True, null=True)),
                ("us_xgbuildup", models.FloatField(blank=True, null=True)),
                ("us_games", models.PositiveIntegerField(blank=True, null=True)),
                ("us_yellow_cards", models.PositiveIntegerField(blank=True, null=True)),
                ("us_red_cards", models.PositiveIntegerField(blank=True, null=True)),
                ("ss_rating", models.FloatField(blank=True, null=True)),
                ("ss_tackles", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ss_interceptions",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ss_clearances", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ss_error_lead_to_goal",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ss_outfielder_blocks",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ss_accurate_passes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ss_inaccurate_passes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ss_total_passes", models.PositiveIntegerField(blank=True, null=True)),
                ("ss_key_passes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ss_accurate_crosses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ss_accurate_long_balls",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("ss_saves", models.PositiveIntegerField(blank=True, null=True)),
                ("ss_clean_sheet", models.PositiveIntegerField(blank=True, null=True)),
                ("ss_penalty_save", models.PositiveIntegerField(blank=True, null=True)),
                ("ss_appearances", models.PositiveIntegerField(blank=True, null=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_display_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_display_team_rows",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_seasons",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_rows",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "merge_ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_rows_merge_run",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "sofascore_ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_rows_sofascore",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predecessors",
                        to="ingestion.mergedplayerseason",
                    ),
                ),
                (
                    "understat_ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_rows_understat",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "is_current"],
                        name="ingestion_m_competi_4db9fe_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "canonical_display_team"],
                        name="ingestion_m_competi_8bc9dc_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "position_group"],
                        name="ingestion_m_competi_6bb9c7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("competition_season", "canonical_player"),
                        name="uniq_current_merged_player_season",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerSeasonClubSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_provider",
                    models.CharField(
                        choices=[
                            ("understat", "Understat"),
                            ("sofascore", "Sofascore"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_spells",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "canonical_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_spells",
                        to="ingestion.competitionseason",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "canonical_player"],
                        name="ingestion_p_competi_790601_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderPlayerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("understat", "Understat"),
                            ("sofascore", "Sofascore"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_player_id", models.CharField(db_index=True, max_length=64)),
                (
                    "match_method",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        default="auto",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_mappings",
                        to="ingestion.canonicalplayer",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_player_id"),
                        name="uniq_provider_player_mapping",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderTeamMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("understat", "Understat"),
                            ("sofascore", "Sofascore"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_team_id", models.CharField(db_index=True, max_length=64)),
                (
                    "match_method",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        default="auto",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canonical_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_mappings",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_team_id"),
                        name="uniq_provider_team_mapping",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="competitionseason",
            constraint=models.UniqueConstraint(
                fields=("competition", "season"), name="uniq_competition_season"
            ),
        ),
        migrations.AddConstraint(
            model_name="sofascoreplayerseasonsource",
            constraint=models.UniqueConstraint(
                fields=("competition_season", "provider_player_id"),
                name="uniq_sofascore_player_per_slice",
            ),
        ),
        migrations.AddConstraint(
            model_name="understatplayerseasonsource",
            constraint=models.UniqueConstraint(
                fields=("competition_season", "provider_player_id"),
                name="uniq_understat_player_per_slice",
            ),
        ),
        migrations.AddConstraint(
            model_name="unmatchedproviderplayer",
            constraint=models.UniqueConstraint(
                fields=("competition_season", "provider", "provider_player_id"),
                name="uniq_unmatched_player_slice",
            ),
        ),
        migrations.AddConstraint(
            model_name="unmatchedproviderteam",
            constraint=models.UniqueConstraint(
                fields=("competition_season", "provider", "provider_team_id"),
                name="uniq_unmatched_team_slice",
            ),
        ),
    ]
