# Generated by Django 5.2.13 on 2026-04-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_accurate_passes_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_big_chances_created",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_runs_out",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_saved_shots_from_inside_the_box",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="accurate_passes_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="big_chances_created",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="group_stats",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="runs_out",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="saved_shots_from_inside_the_box",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="summary_accurate_passes_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="summary_assists",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="summary_expected_goals",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="summary_goals",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="summary_successful_dribbles",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
