# Generated by Django 5.2.13 on 2026-04-12 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_sofascore_reep_csv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reep_sync", "Reep sync"),
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("merge", "Merge"),
                    ("derived", "Derived stats"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PlayerSeasonDerivedStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formula_version",
                    models.CharField(db_index=True, default="v1", max_length=32),
                ),
                (
                    "position_group",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=8,
                    ),
                ),
                ("native_position", models.CharField(blank=True, max_length=64)),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("percentiles_eligible", models.BooleanField(default=False)),
                (
                    "percentiles_ineligibility_reason",
                    models.CharField(blank=True, max_length=64),
                ),
                ("scores_eligible", models.BooleanField(default=False)),
                (
                    "scores_ineligibility_reason",
                    models.CharField(blank=True, max_length=64),
                ),
                ("npxg", models.FloatField(blank=True, null=True)),
                ("npxg_percentile", models.FloatField(blank=True, null=True)),
                ("npxg_per_90", models.FloatField(blank=True, null=True)),
                ("npxg_per_90_percentile", models.FloatField(blank=True, null=True)),
                ("xa", models.FloatField(blank=True, null=True)),
                ("xa_percentile", models.FloatField(blank=True, null=True)),
                ("xa_per_90", models.FloatField(blank=True, null=True)),
                ("xa_per_90_percentile", models.FloatField(blank=True, null=True)),
                ("xgchain", models.FloatField(blank=True, null=True)),
                ("xgchain_percentile", models.FloatField(blank=True, null=True)),
                ("xgchain_per_90", models.FloatField(blank=True, null=True)),
                ("xgchain_per_90_percentile", models.FloatField(blank=True, null=True)),
                ("xgbuildup", models.FloatField(blank=True, null=True)),
                ("xgbuildup_percentile", models.FloatField(blank=True, null=True)),
                ("xgbuildup_per_90", models.FloatField(blank=True, null=True)),
                (
                    "xgbuildup_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("shots_per_90", models.FloatField(blank=True, null=True)),
                ("shots_per_90_percentile", models.FloatField(blank=True, null=True)),
                ("key_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "key_passes_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "big_chances_created_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "big_chances_created_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "successful_dribbles_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "successful_dribbles_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("completed_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "completed_passes_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("goals_minus_xg", models.FloatField(blank=True, null=True)),
                ("goals_minus_xg_percentile", models.FloatField(blank=True, null=True)),
                ("goals_minus_npxg", models.FloatField(blank=True, null=True)),
                (
                    "goals_minus_npxg_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("npxg_per_shot", models.FloatField(blank=True, null=True)),
                ("npxg_per_shot_percentile", models.FloatField(blank=True, null=True)),
                ("xa_per_key_pass", models.FloatField(blank=True, null=True)),
                (
                    "xa_per_key_pass_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("buildup_share", models.FloatField(blank=True, null=True)),
                ("buildup_share_percentile", models.FloatField(blank=True, null=True)),
                ("chance_involvement_per_90", models.FloatField(blank=True, null=True)),
                (
                    "chance_involvement_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("pass_accuracy", models.FloatField(blank=True, null=True)),
                ("pass_accuracy_percentile", models.FloatField(blank=True, null=True)),
                ("tackles_per_90", models.FloatField(blank=True, null=True)),
                ("tackles_per_90_percentile", models.FloatField(blank=True, null=True)),
                ("interceptions_per_90", models.FloatField(blank=True, null=True)),
                (
                    "interceptions_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("clearances_per_90", models.FloatField(blank=True, null=True)),
                (
                    "clearances_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("blocks_per_90", models.FloatField(blank=True, null=True)),
                ("blocks_per_90_percentile", models.FloatField(blank=True, null=True)),
                ("defensive_action_density", models.FloatField(blank=True, null=True)),
                (
                    "defensive_action_density_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("finishing_score_raw", models.FloatField(blank=True, null=True)),
                ("finishing_score", models.FloatField(blank=True, null=True)),
                ("creation_score_raw", models.FloatField(blank=True, null=True)),
                ("creation_score", models.FloatField(blank=True, null=True)),
                ("buildup_score_raw", models.FloatField(blank=True, null=True)),
                ("buildup_score", models.FloatField(blank=True, null=True)),
                ("ball_winning_score_raw", models.FloatField(blank=True, null=True)),
                ("ball_winning_score", models.FloatField(blank=True, null=True)),
                ("involvement_score_raw", models.FloatField(blank=True, null=True)),
                ("involvement_score", models.FloatField(blank=True, null=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_display_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_display_team_rows",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_seasons",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_rows",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "derived_ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "merged_player_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_rows",
                        to="ingestion.mergedplayerseason",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predecessor_rows",
                        to="ingestion.playerseasonderivedstats",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "is_current"],
                        name="ingestion_p_competi_dea495_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "position_group"],
                        name="ingestion_p_competi_3e6367_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "canonical_display_team"],
                        name="ingestion_p_competi_0e9b56_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "formula_version"],
                        name="ingestion_p_competi_df8688_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("competition_season", "canonical_player"),
                        name="uniq_current_derived_player_season",
                    )
                ],
            },
        ),
    ]
