# Generated by Django 5.1.7 on 2026-04-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0005_goals_assists_per_90"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_aerial_duels_won",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_ball_recoveries",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_fouls",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_ground_duels_won",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_offsides",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_shots_off_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_shots_on_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_successful_dribbles_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_tackles_won",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_tackles_won_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="aerial_duels_won",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="ball_recoveries",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="fouls",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="ground_duels_won",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="offsides",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="shots_off_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="shots_on_target",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="successful_dribbles_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="tackles_won",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="tackles_won_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
