# Generated by Django 5.1.7 on 2026-04-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0006_mergedplayerseason_ss_aerial_duels_won_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="aerial_duels_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="aerial_duels_won_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="ball_recoveries",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="ball_recoveries_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="fouls",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="fouls_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="ground_duels_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="ground_duels_won_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="offsides",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="offsides_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="shots_off_target",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="shots_off_target_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="shots_on_target",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="shots_on_target_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="successful_dribbles_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="successful_dribbles_percentage_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="tackles_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="tackles_won_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="tackles_won_percentage_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="tackles_won_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
