# Generated by Django 5.2.13 on 2026-04-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0008_v2_score_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="finishing_shrunk_delta_per_shot",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="finishing_shrunk_delta_per_shot_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="sot_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="sot_rate_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
