# Generated by Django 5.1.7 on 2026-04-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0009_finishing_score_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reep_sync", "Reep sync"),
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("merge", "Merge"),
                    ("derived", "Derived stats"),
                    ("galaxy", "Galaxy embeddings"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PlayerSeasonEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_group",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=8,
                    ),
                ),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cluster_id",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("umap_x", models.FloatField()),
                ("umap_y", models.FloatField()),
                ("umap_z", models.FloatField()),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_display_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedding_display_team_rows",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_seasons",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_rows",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "embedding_ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedding_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predecessor_embedding_rows",
                        to="ingestion.playerseasonembedding",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "is_current"],
                        name="ingestion_p_competi_a902ce_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "position_group"],
                        name="ingestion_p_competi_174fe0_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "canonical_display_team"],
                        name="ingestion_p_competi_45e358_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "cluster_id"],
                        name="ingestion_p_competi_4d9303_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("competition_season", "canonical_player"),
                        name="uniq_current_embedding_player_season",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerSeasonSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity", models.FloatField()),
                ("rank", models.PositiveSmallIntegerField()),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_players",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_rows",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "similar_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_to_players",
                        to="ingestion.canonicalplayer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "is_current"],
                        name="ingestion_p_competi_9a9fb2_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "canonical_player", "rank"],
                        name="ingestion_p_competi_2a633f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("competition_season", "canonical_player", "rank"),
                        name="uniq_current_similarity_rank",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=(
                            "competition_season",
                            "canonical_player",
                            "similar_player",
                        ),
                        name="uniq_current_similarity_pair",
                    ),
                ],
            },
        ),
    ]
