# Generated by Django 5.2.13 on 2026-04-17 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0011_playerseasonembedding_cluster_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSeasonGkDerivedStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formula_version",
                    models.CharField(db_index=True, default="gk_v1", max_length=32),
                ),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("appearances", models.PositiveIntegerField(blank=True, null=True)),
                ("percentiles_eligible", models.BooleanField(default=False)),
                (
                    "percentiles_ineligibility_reason",
                    models.CharField(blank=True, max_length=64),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("rating_percentile", models.FloatField(blank=True, null=True)),
                ("saves", models.PositiveIntegerField(blank=True, null=True)),
                ("saves_percentile", models.FloatField(blank=True, null=True)),
                ("saves_per_90", models.FloatField(blank=True, null=True)),
                ("saves_per_90_percentile", models.FloatField(blank=True, null=True)),
                ("clean_sheets", models.PositiveIntegerField(blank=True, null=True)),
                ("clean_sheets_percentile", models.FloatField(blank=True, null=True)),
                ("clean_sheet_rate", models.FloatField(blank=True, null=True)),
                (
                    "clean_sheet_rate_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("penalty_saves", models.PositiveIntegerField(blank=True, null=True)),
                ("penalty_saves_percentile", models.FloatField(blank=True, null=True)),
                (
                    "saved_shots_inside_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "saved_shots_inside_box_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "saved_shots_inside_box_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "saved_shots_inside_box_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("runs_out", models.PositiveIntegerField(blank=True, null=True)),
                ("runs_out_percentile", models.FloatField(blank=True, null=True)),
                ("runs_out_per_90", models.FloatField(blank=True, null=True)),
                (
                    "runs_out_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("pass_accuracy", models.FloatField(blank=True, null=True)),
                ("pass_accuracy_percentile", models.FloatField(blank=True, null=True)),
                ("completed_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "completed_passes_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "accurate_long_balls_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "accurate_long_balls_per_90_percentile",
                    models.FloatField(blank=True, null=True),
                ),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_display_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gk_derived_display_team_rows",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gk_derived_seasons",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gk_derived_rows",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "derived_ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gk_derived_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "merged_player_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gk_derived_rows",
                        to="ingestion.mergedplayerseason",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predecessor_gk_derived_rows",
                        to="ingestion.playerseasongkderivedstats",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "is_current"],
                        name="ingestion_p_competi_e49c59_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "canonical_display_team"],
                        name="ingestion_p_competi_f24ff7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("competition_season", "canonical_player"),
                        name="uniq_current_gk_derived_player_season",
                    )
                ],
            },
        ),
    ]
