# Generated by Django 5.2.13 on 2026-04-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0012_player_season_gk_derived_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionseason",
            name="expected_team_count",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="competitionseason",
            name="min_merged_team_count",
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name="competitionseason",
            name="min_team_stats_coverage_count",
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name="ingestionrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reep_sync", "Reep sync"),
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("sofascore_team", "Sofascore team"),
                    ("merge", "Merge"),
                    ("team_merge", "Team merge"),
                    ("derived", "Derived stats"),
                    ("galaxy", "Galaxy embeddings"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MergedTeamSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches", models.PositiveIntegerField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(blank=True, null=True)),
                ("wins", models.PositiveIntegerField(blank=True, null=True)),
                ("draws", models.PositiveIntegerField(blank=True, null=True)),
                ("losses", models.PositiveIntegerField(blank=True, null=True)),
                ("goals_for", models.PositiveIntegerField(blank=True, null=True)),
                ("goals_against", models.PositiveIntegerField(blank=True, null=True)),
                ("goal_difference", models.IntegerField(blank=True, null=True)),
                ("assists", models.PositiveIntegerField(blank=True, null=True)),
                ("average_ball_possession", models.FloatField(blank=True, null=True)),
                ("clean_sheets", models.PositiveIntegerField(blank=True, null=True)),
                ("own_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("shots", models.PositiveIntegerField(blank=True, null=True)),
                ("shots_on_target", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "shots_off_target",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("shots_against", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "shots_on_target_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shots_from_inside_the_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shots_from_inside_the_box_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shots_from_outside_the_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shots_from_outside_the_box_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("big_chances", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "big_chances_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "big_chances_created",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "big_chances_created_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "big_chances_missed",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("corners", models.PositiveIntegerField(blank=True, null=True)),
                ("corners_against", models.PositiveIntegerField(blank=True, null=True)),
                ("accurate_passes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "accurate_passes_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_passes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "accurate_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "accurate_long_balls",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_long_balls",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "accurate_long_balls_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "accurate_crosses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_crosses", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "accurate_crosses_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("ball_recovery", models.PositiveIntegerField(blank=True, null=True)),
                ("possession_lost", models.PositiveIntegerField(blank=True, null=True)),
                ("tackles", models.PositiveIntegerField(blank=True, null=True)),
                ("tackles_against", models.PositiveIntegerField(blank=True, null=True)),
                ("interceptions", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "interceptions_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("clearances", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "clearances_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("saves", models.PositiveIntegerField(blank=True, null=True)),
                ("duels_won", models.PositiveIntegerField(blank=True, null=True)),
                ("duels_won_percentage", models.FloatField(blank=True, null=True)),
                (
                    "aerial_duels_won",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "aerial_duels_won_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "ground_duels_won",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ground_duels_won_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "successful_dribbles",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fouls", models.PositiveIntegerField(blank=True, null=True)),
                ("yellow_cards", models.PositiveIntegerField(blank=True, null=True)),
                ("red_cards", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "yellow_cards_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "red_cards_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("offsides", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "offsides_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("penalties_taken", models.PositiveIntegerField(blank=True, null=True)),
                ("penalty_goals", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "penalty_goals_conceded",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "goals_from_inside_the_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "goals_from_outside_the_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("headed_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("hit_woodwork", models.PositiveIntegerField(blank=True, null=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_team_seasons",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_team_rows",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "sofascore_team_ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_team_rows_sofascore",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_predecessors",
                        to="ingestion.mergedteamseason",
                    ),
                ),
                (
                    "team_merge_ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_team_rows_merge_run",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "is_current"],
                        name="ingestion_m_competi_f23df4_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "rank"],
                        name="ingestion_m_competi_84e425_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("competition_season", "canonical_team"),
                        name="uniq_current_merged_team_season",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SofascoreTeamSeasonSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_team_id", models.CharField(db_index=True, max_length=64)),
                ("team_name", models.CharField(blank=True, max_length=200)),
                ("standings_row_json", models.JSONField(blank=True, default=dict)),
                ("overall_stats_json", models.JSONField(blank=True, default=dict)),
                (
                    "has_overall_stats",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("matches", models.PositiveIntegerField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(blank=True, null=True)),
                ("wins", models.PositiveIntegerField(blank=True, null=True)),
                ("draws", models.PositiveIntegerField(blank=True, null=True)),
                ("losses", models.PositiveIntegerField(blank=True, null=True)),
                ("goals_for", models.PositiveIntegerField(blank=True, null=True)),
                ("goals_against", models.PositiveIntegerField(blank=True, null=True)),
                ("goal_difference", models.IntegerField(blank=True, null=True)),
                ("assists", models.PositiveIntegerField(blank=True, null=True)),
                ("average_ball_possession", models.FloatField(blank=True, null=True)),
                ("clean_sheets", models.PositiveIntegerField(blank=True, null=True)),
                ("own_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("shots", models.PositiveIntegerField(blank=True, null=True)),
                ("shots_on_target", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "shots_off_target",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("shots_against", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "shots_on_target_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shots_from_inside_the_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shots_from_inside_the_box_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shots_from_outside_the_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "shots_from_outside_the_box_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("big_chances", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "big_chances_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "big_chances_created",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "big_chances_created_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "big_chances_missed",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("corners", models.PositiveIntegerField(blank=True, null=True)),
                ("corners_against", models.PositiveIntegerField(blank=True, null=True)),
                ("accurate_passes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "accurate_passes_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_passes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "accurate_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "accurate_long_balls",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_long_balls",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "accurate_long_balls_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "accurate_crosses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_crosses", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "accurate_crosses_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("ball_recovery", models.PositiveIntegerField(blank=True, null=True)),
                ("possession_lost", models.PositiveIntegerField(blank=True, null=True)),
                ("tackles", models.PositiveIntegerField(blank=True, null=True)),
                ("tackles_against", models.PositiveIntegerField(blank=True, null=True)),
                ("interceptions", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "interceptions_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("clearances", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "clearances_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("saves", models.PositiveIntegerField(blank=True, null=True)),
                ("duels_won", models.PositiveIntegerField(blank=True, null=True)),
                ("duels_won_percentage", models.FloatField(blank=True, null=True)),
                (
                    "aerial_duels_won",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "aerial_duels_won_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "ground_duels_won",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ground_duels_won_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "successful_dribbles",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fouls", models.PositiveIntegerField(blank=True, null=True)),
                ("yellow_cards", models.PositiveIntegerField(blank=True, null=True)),
                ("red_cards", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "yellow_cards_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "red_cards_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("offsides", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "offsides_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("penalties_taken", models.PositiveIntegerField(blank=True, null=True)),
                ("penalty_goals", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "penalty_goals_conceded",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "goals_from_inside_the_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "goals_from_outside_the_box",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("headed_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("hit_woodwork", models.PositiveIntegerField(blank=True, null=True)),
                ("awarded_matches", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "blocked_scoring_attempt",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "blocked_scoring_attempt_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "errors_leading_to_goal",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "errors_leading_to_goal_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "errors_leading_to_shot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "errors_leading_to_shot_against",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("free_kicks", models.PositiveIntegerField(blank=True, null=True)),
                ("goal_kicks", models.PositiveIntegerField(blank=True, null=True)),
                ("throw_ins", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "canonical_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sofascore_team_sources",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sofascore_team_sources",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sofascore_team_rows",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "canonical_team"],
                        name="ingestion_s_competi_3c3e4b_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "has_overall_stats"],
                        name="ingestion_s_competi_b2ece8_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competition_season", "provider_team_id"),
                        name="uniq_sofascore_team_per_slice",
                    )
                ],
            },
        ),
    ]
