# Generated by Django 5.1.7 on 2026-04-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0014_team_expected_goals_expected_assists"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedplayerseason",
            name="secondary_display_team_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Other canonical team ids from Understat multi-club season row (comma-separated team_title), excluding the primary SofaScore display team.",
            ),
        ),
    ]
