# Generated by Django 5.1.7 on 2026-04-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0015_merged_player_secondary_teams_sofascore_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="understatplayerseasonsource",
            name="provider_team_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered Understat team ids for each comma-separated club in team_title (from league teams payload).",
            ),
        ),
    ]
