# Generated by Django 5.2.13 on 2026-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0017_competitionseason_capabilities_and_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergedteamseason",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sofascoreteamseasonsource",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
