# Generated by Django 5.2.13 on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0018_alter_mergedteamseason_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="summary_expected_assists",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sofascoreplayerseasonsource",
            name="total_shots",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_assists",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_expected_assists",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_expected_goals",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_goals",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mergedplayerseason",
            name="ss_total_shots",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
