# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0019_sofascore_player_attacking_merge_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="xg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="xg_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="xg_per_90",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonderivedstats",
            name="xg_per_90_percentile",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
