# Generated by Django 5.2.13 on 2026-05-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0020_playerseasonderivedstats_xg"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalaxyArchetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archetype_key", models.CharField(max_length=64)),
                (
                    "position_group",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=8,
                    ),
                ),
                ("cluster_id", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=80)),
                ("color", models.CharField(blank=True, default="", max_length=16)),
                ("size", models.PositiveIntegerField(default=0)),
                ("centroid", models.JSONField(blank=True, default=dict)),
                ("feature_signature", models.JSONField(blank=True, default=dict)),
                ("representative_players", models.JSONField(blank=True, default=list)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GalaxyPlayerEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("galaxy_player_id", models.CharField(db_index=True, max_length=80)),
                (
                    "position_group",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=8,
                    ),
                ),
                ("native_position", models.CharField(blank=True, max_length=64)),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "primary_archetype_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "primary_archetype_confidence",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "secondary_archetype_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "secondary_archetype_confidence",
                    models.FloatField(blank=True, null=True),
                ),
                ("archetype_margin", models.FloatField(blank=True, null=True)),
                ("archetype_diagnostics", models.JSONField(blank=True, default=dict)),
                ("feature_values", models.JSONField(blank=True, default=dict)),
                ("scaled_features", models.JSONField(blank=True, default=dict)),
                ("imputed_features", models.JSONField(blank=True, default=list)),
                ("umap_x", models.FloatField()),
                ("umap_y", models.FloatField()),
                ("umap_z", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_display_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galaxy_display_team_rows",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galaxy_embeddings",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galaxy_player_embeddings",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "derived_stats",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galaxy_embeddings",
                        to="ingestion.playerseasonderivedstats",
                    ),
                ),
                (
                    "primary_archetype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_players",
                        to="ingestion.galaxyarchetype",
                    ),
                ),
                (
                    "secondary_archetype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_players",
                        to="ingestion.galaxyarchetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalaxySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_code", models.CharField(db_index=True, max_length=32)),
                ("season_label", models.CharField(db_index=True, max_length=32)),
                (
                    "model_version",
                    models.CharField(db_index=True, default="galaxy_v2", max_length=32),
                ),
                (
                    "feature_profile",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("min_minutes", models.PositiveIntegerField(default=450)),
                ("default_min_minutes", models.PositiveIntegerField(default=900)),
                ("top_k", models.PositiveSmallIntegerField(default=15)),
                (
                    "included_competition_season_ids",
                    models.JSONField(blank=True, default=list),
                ),
                ("excluded_competitions", models.JSONField(blank=True, default=list)),
                ("feature_names", models.JSONField(blank=True, default=list)),
                ("feature_weights", models.JSONField(blank=True, default=dict)),
                ("feature_groups", models.JSONField(blank=True, default=dict)),
                ("imputation_values", models.JSONField(blank=True, default=dict)),
                ("scaling", models.JSONField(blank=True, default=dict)),
                ("position_penalties", models.JSONField(blank=True, default=dict)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galaxy_snapshots",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalaxySimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("base_distance", models.FloatField()),
                ("distance", models.FloatField()),
                ("position_multiplier", models.FloatField(default=1.0)),
                ("candidate_percentile_score", models.FloatField()),
                ("absolute_fit_score", models.FloatField()),
                ("profile_match_score", models.FloatField()),
                ("weak_absolute_fit", models.BooleanField(default=False)),
                (
                    "match_context",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("explanation", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "similar_embedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_to_rows",
                        to="ingestion.galaxyplayerembedding",
                    ),
                ),
                (
                    "source_embedding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_rows",
                        to="ingestion.galaxyplayerembedding",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities",
                        to="ingestion.galaxysnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="galaxyplayerembedding",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_embeddings",
                to="ingestion.galaxysnapshot",
            ),
        ),
        migrations.AddField(
            model_name="galaxyarchetype",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archetypes",
                to="ingestion.galaxysnapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxysnapshot",
            index=models.Index(
                fields=["scope_code", "season_label", "is_current"],
                name="ingestion_g_scope_c_01df8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxysnapshot",
            index=models.Index(
                fields=["feature_profile"], name="ingestion_g_feature_584e75_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="galaxysnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("scope_code", "season_label"),
                name="uniq_current_galaxy_snapshot_scope_season",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxysimilarity",
            index=models.Index(
                fields=["snapshot", "source_embedding", "rank"],
                name="ingestion_g_snapsho_5d28e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxysimilarity",
            index=models.Index(
                fields=["snapshot", "profile_match_score"],
                name="ingestion_g_snapsho_acc110_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="galaxysimilarity",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "source_embedding", "rank"),
                name="uniq_galaxy_similarity_rank_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="galaxysimilarity",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "source_embedding", "similar_embedding"),
                name="uniq_galaxy_similarity_pair_per_snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxyplayerembedding",
            index=models.Index(
                fields=["snapshot", "position_group"],
                name="ingestion_g_snapsho_e06d00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxyplayerembedding",
            index=models.Index(
                fields=["snapshot", "canonical_display_team"],
                name="ingestion_g_snapsho_39e60e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxyplayerembedding",
            index=models.Index(
                fields=["snapshot", "primary_archetype"],
                name="ingestion_g_snapsho_957101_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxyplayerembedding",
            index=models.Index(
                fields=["competition_season", "canonical_player"],
                name="ingestion_g_competi_d259f6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="galaxyplayerembedding",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "galaxy_player_id"),
                name="uniq_galaxy_player_id_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="galaxyplayerembedding",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "competition_season", "canonical_player"),
                name="uniq_galaxy_competition_player_per_snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxyarchetype",
            index=models.Index(
                fields=["snapshot", "position_group"],
                name="ingestion_g_snapsho_5f8e8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="galaxyarchetype",
            index=models.Index(
                fields=["snapshot", "cluster_id"], name="ingestion_g_snapsho_14aa55_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="galaxyarchetype",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "archetype_key"),
                name="uniq_galaxy_archetype_key_per_snapshot",
            ),
        ),
    ]
