# Generated by Django 5.2.13 on 2026-05-28 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0023_daily_refresh_orchestration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reep_sync", "Reep sync"),
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("sofascore_team", "Sofascore team"),
                    ("position_resolution", "Position resolution"),
                    ("merge", "Merge"),
                    ("team_merge", "Team merge"),
                    ("derived", "Derived stats"),
                    ("galaxy", "Galaxy embeddings"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PlayerPositionResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("existing_source", "Existing source"),
                            ("historical_player", "Historical player"),
                            ("sofascore_roster", "Sofascore roster"),
                            ("sofascore_profile", "Sofascore profile"),
                            ("manual", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("raw_position", models.CharField(max_length=64)),
                (
                    "position_group",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                            ("UNK", "Unknown"),
                        ],
                        max_length=8,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_resolutions",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "canonical_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_position_resolutions",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_resolutions",
                        to="ingestion.competitionseason",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "position_group"],
                        name="ingestion_p_competi_c4f9c1_idx",
                    ),
                    models.Index(
                        fields=["source", "fetched_at"],
                        name="ingestion_p_source_f8d72a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competition_season", "canonical_player"),
                        name="uniq_position_resolution_per_player_slice",
                    )
                ],
            },
        ),
    ]
