# Generated by Django 5.2.13 on 2026-07-27 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0025_materializedapipayload_rendered_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionseason",
            name="has_whoscored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="competitionseason",
            name="whoscored_expected_match_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competitionseason",
            name="whoscored_league",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="competitionseason",
            name="whoscored_season",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="ingestionrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reep_sync", "Reep sync"),
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("sofascore_team", "Sofascore team"),
                    ("position_resolution", "Position resolution"),
                    ("merge", "Merge"),
                    ("team_merge", "Team merge"),
                    ("derived", "Derived stats"),
                    ("galaxy", "Galaxy embeddings"),
                    ("whoscored_fetch", "WhoScored fetch"),
                    ("event_profiles", "Event profiles"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="playerseasonclubspell",
            name="source_provider",
            field=models.CharField(
                choices=[
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("whoscored", "WhoScored"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="providerplayermapping",
            name="provider",
            field=models.CharField(
                choices=[
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("whoscored", "WhoScored"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="providerteammapping",
            name="provider",
            field=models.CharField(
                choices=[
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("whoscored", "WhoScored"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="unmatchedproviderplayer",
            name="provider",
            field=models.CharField(
                choices=[
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("whoscored", "WhoScored"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="unmatchedproviderteam",
            name="provider",
            field=models.CharField(
                choices=[
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("whoscored", "WhoScored"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ProviderMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("understat", "Understat"),
                            ("sofascore", "Sofascore"),
                            ("whoscored", "WhoScored"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_match_id", models.CharField(max_length=64)),
                ("kickoff_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                            ("postponed", "Postponed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("home_provider_team_id", models.CharField(max_length=64)),
                ("away_provider_team_id", models.CharField(max_length=64)),
                ("home_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_away_matches",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_matches",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_home_matches",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_index", models.PositiveIntegerField()),
                (
                    "provider_event_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("provider_team_id", models.CharField(max_length=64)),
                (
                    "provider_player_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "First half"),
                            (2, "Second half"),
                            (3, "First period of extra time"),
                            (4, "Second period of extra time"),
                            (5, "Penalty shootout"),
                            (6, "Post-game"),
                        ],
                        default=0,
                    ),
                ),
                ("minute", models.PositiveSmallIntegerField()),
                (
                    "second",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ]
                    ),
                ),
                (
                    "expanded_minute",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("match_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "event_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Pass"),
                            (2, "Ball touch"),
                            (3, "Take-on"),
                            (4, "Shot"),
                            (5, "Ball recovery"),
                            (6, "Tackle"),
                            (7, "Interception"),
                            (8, "Clearance"),
                            (9, "Blocked pass"),
                            (10, "Aerial"),
                            (11, "Challenge"),
                            (12, "Dispossessed"),
                            (13, "Foul"),
                            (14, "Save"),
                            (15, "Offside"),
                            (16, "Card"),
                            (17, "Substitution"),
                            (18, "Administrative"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "source_event_type_id",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("outcome_successful", models.BooleanField(blank=True, null=True)),
                (
                    "x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "end_x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "end_y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "goal_mouth_y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "goal_mouth_z",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "blocked_x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "blocked_y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                ("is_touch", models.BooleanField(default=False)),
                ("is_key_pass", models.BooleanField(default=False)),
                ("is_shot_assist", models.BooleanField(default=False)),
                ("is_intentional_assist", models.BooleanField(default=False)),
                ("is_cross", models.BooleanField(default=False)),
                ("is_long_ball", models.BooleanField(default=False)),
                ("is_chipped", models.BooleanField(default=False)),
                ("is_head_pass", models.BooleanField(default=False)),
                ("is_through_ball", models.BooleanField(default=False)),
                ("is_throw_in", models.BooleanField(default=False)),
                ("is_corner", models.BooleanField(default=False)),
                ("is_free_kick", models.BooleanField(default=False)),
                ("is_set_piece", models.BooleanField(default=False)),
                ("is_regular_play", models.BooleanField(default=False)),
                ("is_big_chance", models.BooleanField(default=False)),
                (
                    "body_part",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Right foot"),
                            (2, "Left foot"),
                            (3, "Head"),
                            (4, "Other"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "shot_situation",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Open play"),
                            (2, "Set piece"),
                            (3, "Corner"),
                            (4, "Direct free kick"),
                            (5, "Penalty"),
                            (6, "Fast break"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "shot_outcome",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Goal"),
                            (2, "Saved"),
                            (3, "Blocked"),
                            (4, "Off target"),
                            (5, "Woodwork"),
                        ],
                        default=0,
                    ),
                ),
                ("is_progressive_pass", models.BooleanField(default=False)),
                ("is_final_third_entry", models.BooleanField(default=False)),
                ("is_box_entry", models.BooleanField(default=False)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_events",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ingestion.providermatch",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_events",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("db", "Database"), ("object", "Object storage")],
                        default="db",
                        max_length=16,
                    ),
                ),
                ("payload_gzip", models.BinaryField(blank=True, null=True)),
                ("object_key", models.CharField(blank=True, max_length=512, null=True)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("payload_size_bytes", models.PositiveIntegerField()),
                ("uncompressed_size_bytes", models.PositiveIntegerField()),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[("preliminary", "Preliminary"), ("final", "Final")],
                        max_length=16,
                    ),
                ),
                (
                    "preliminary_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("preliminary_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "final_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("final_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField()),
                (
                    "provider_match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payload",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamSeasonEventProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formula_version",
                    models.CharField(
                        db_index=True, default="event_profiles_v1", max_length=32
                    ),
                ),
                ("observed_match_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "expected_match_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("coverage", models.FloatField(blank=True, null=True)),
                ("valid_location_actions", models.PositiveIntegerField(default=0)),
                ("touches", models.PositiveIntegerField(default=0)),
                ("pass_attempts", models.PositiveIntegerField(default=0)),
                ("pass_completions", models.PositiveIntegerField(default=0)),
                ("progressive_pass_attempts", models.PositiveIntegerField(default=0)),
                (
                    "progressive_pass_completions",
                    models.PositiveIntegerField(default=0),
                ),
                ("final_third_entries", models.PositiveIntegerField(default=0)),
                ("box_entries", models.PositiveIntegerField(default=0)),
                ("key_passes", models.PositiveIntegerField(default=0)),
                ("crosses", models.PositiveIntegerField(default=0)),
                ("long_balls", models.PositiveIntegerField(default=0)),
                ("shots_for", models.PositiveIntegerField(default=0)),
                ("goals_for", models.PositiveIntegerField(default=0)),
                ("big_chance_shots_for", models.PositiveIntegerField(default=0)),
                ("shots_against", models.PositiveIntegerField(default=0)),
                ("goals_against", models.PositiveIntegerField(default=0)),
                ("big_chance_shots_against", models.PositiveIntegerField(default=0)),
                ("take_ons_attempted", models.PositiveIntegerField(default=0)),
                ("take_ons_successful", models.PositiveIntegerField(default=0)),
                ("defensive_actions", models.PositiveIntegerField(default=0)),
                ("action_grid", models.JSONField(blank=True, default=list)),
                ("opponent_action_grid", models.JSONField(blank=True, default=list)),
                ("pass_flow", models.JSONField(blank=True, default=list)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_event_profiles",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "materialized_ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_event_profiles",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_event_profiles",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerSeasonEventProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "split_type",
                    models.CharField(
                        choices=[("season_total", "Season total"), ("team", "Team")],
                        max_length=16,
                    ),
                ),
                (
                    "formula_version",
                    models.CharField(
                        db_index=True, default="event_profiles_v1", max_length=32
                    ),
                ),
                ("observed_match_count", models.PositiveSmallIntegerField(default=0)),
                ("observed_event_minutes", models.PositiveIntegerField(default=0)),
                ("minutes", models.PositiveIntegerField(default=0)),
                ("valid_location_actions", models.PositiveIntegerField(default=0)),
                ("touches", models.PositiveIntegerField(default=0)),
                ("pass_attempts", models.PositiveIntegerField(default=0)),
                ("pass_completions", models.PositiveIntegerField(default=0)),
                ("progressive_pass_attempts", models.PositiveIntegerField(default=0)),
                (
                    "progressive_pass_completions",
                    models.PositiveIntegerField(default=0),
                ),
                ("final_third_entries", models.PositiveIntegerField(default=0)),
                ("box_entries", models.PositiveIntegerField(default=0)),
                ("key_passes", models.PositiveIntegerField(default=0)),
                ("crosses", models.PositiveIntegerField(default=0)),
                ("long_balls", models.PositiveIntegerField(default=0)),
                ("shots", models.PositiveIntegerField(default=0)),
                ("goals", models.PositiveIntegerField(default=0)),
                ("big_chance_shots", models.PositiveIntegerField(default=0)),
                ("take_ons_attempted", models.PositiveIntegerField(default=0)),
                ("take_ons_successful", models.PositiveIntegerField(default=0)),
                ("defensive_actions", models.PositiveIntegerField(default=0)),
                (
                    "average_touch_x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "average_touch_y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                ("action_grid", models.JSONField(blank=True, default=list)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_event_profiles",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "materialized_ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_event_profiles",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_event_profiles",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_season_event_profiles",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["competition_season", "player", "is_current"],
                        name="player_event_profile_idx",
                    ),
                    models.Index(
                        fields=["competition_season", "team", "is_current"],
                        name="player_event_team_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("split_type", "season_total"), ("team__isnull", True)
                            ),
                            models.Q(("split_type", "team"), ("team__isnull", False)),
                            _connector="OR",
                        ),
                        name="player_event_profile_scope",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_current", True), ("split_type", "season_total")
                        ),
                        fields=("competition_season", "player"),
                        name="uniq_cur_player_event_total",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_current", True), ("split_type", "team")
                        ),
                        fields=("competition_season", "player", "team"),
                        name="uniq_cur_player_event_team",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="providermatch",
            index=models.Index(
                fields=["competition_season", "kickoff_at"],
                name="prov_match_slice_kick_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatch",
            index=models.Index(
                fields=["competition_season", "status"],
                name="prov_match_slice_stat_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatch",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_match_id"), name="uniq_provider_match"
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("away_score__isnull", True), ("home_score__isnull", True)
                    ),
                    models.Q(
                        ("away_score__isnull", False), ("home_score__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="provider_match_scores_paired",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchevent",
            index=models.Index(
                fields=["player", "event_type", "provider_match"],
                name="prov_event_player_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchevent",
            index=models.Index(
                fields=["team", "event_type", "provider_match"],
                name="prov_event_team_type_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchevent",
            constraint=models.UniqueConstraint(
                fields=("provider_match", "event_index"),
                name="uniq_provider_match_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("second__gte", 0), ("second__lte", 59)),
                name="provider_event_second_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("x__isnull", True),
                        models.Q(("x__gte", 0), ("x__lte", 10000)),
                        _connector="OR",
                    ),
                    models.Q(
                        ("y__isnull", True),
                        models.Q(("y__gte", 0), ("y__lte", 10000)),
                        _connector="OR",
                    ),
                    models.Q(
                        ("end_x__isnull", True),
                        models.Q(("end_x__gte", 0), ("end_x__lte", 10000)),
                        _connector="OR",
                    ),
                    models.Q(
                        ("end_y__isnull", True),
                        models.Q(("end_y__gte", 0), ("end_y__lte", 10000)),
                        _connector="OR",
                    ),
                    models.Q(
                        ("goal_mouth_y__isnull", True),
                        models.Q(
                            ("goal_mouth_y__gte", 0), ("goal_mouth_y__lte", 10000)
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("goal_mouth_z__isnull", True),
                        models.Q(
                            ("goal_mouth_z__gte", 0), ("goal_mouth_z__lte", 10000)
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("blocked_x__isnull", True),
                        models.Q(("blocked_x__gte", 0), ("blocked_x__lte", 10000)),
                        _connector="OR",
                    ),
                    models.Q(
                        ("blocked_y__isnull", True),
                        models.Q(("blocked_y__gte", 0), ("blocked_y__lte", 10000)),
                        _connector="OR",
                    ),
                ),
                name="provider_event_coords_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchpayload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("object_key__isnull", True),
                        ("payload_gzip__isnull", False),
                        ("storage_backend", "db"),
                    ),
                    models.Q(
                        ("object_key__isnull", False),
                        ("payload_gzip__isnull", True),
                        ("storage_backend", "object"),
                    ),
                    _connector="OR",
                ),
                name="provider_payload_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchpayload",
            constraint=models.CheckConstraint(
                condition=(
                    (
                        models.Q(
                            preliminary_sha256__isnull=True,
                            preliminary_fetched_at__isnull=True,
                        )
                        | models.Q(
                            preliminary_sha256__isnull=False,
                            preliminary_fetched_at__isnull=False,
                        )
                    )
                    & (
                        models.Q(
                            final_sha256__isnull=True,
                            final_fetched_at__isnull=True,
                        )
                        | models.Q(
                            final_sha256__isnull=False,
                            final_fetched_at__isnull=False,
                        )
                    )
                    & (
                        models.Q(
                            lifecycle_state="preliminary",
                            preliminary_sha256__isnull=False,
                            preliminary_fetched_at__isnull=False,
                            final_sha256__isnull=True,
                            final_fetched_at__isnull=True,
                            payload_sha256=models.F("preliminary_sha256"),
                        )
                        | models.Q(
                            lifecycle_state="final",
                            final_sha256__isnull=False,
                            final_fetched_at__isnull=False,
                            payload_sha256=models.F("final_sha256"),
                        )
                    )
                ),
                name="provider_payload_lifecycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchpayload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    payload_size_bytes__gt=0,
                    uncompressed_size_bytes__gt=0,
                ),
                name="provider_payload_sizes_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="teamseasoneventprofile",
            index=models.Index(
                fields=["competition_season", "team", "is_current"],
                name="team_event_profile_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamseasoneventprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("coverage__isnull", True),
                    models.Q(("coverage__gte", 0.0), ("coverage__lte", 1.0)),
                    _connector="OR",
                ),
                name="team_event_coverage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamseasoneventprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("competition_season", "team"),
                name="uniq_cur_team_event_profile",
            ),
        ),
    ]
