# Generated by Django 5.2.13 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ingestion", "0027_competition_publication_taxonomy_eligibility")]

    operations = [
        migrations.AddField(
            model_name="providermatchevent",
            name="is_defensive",
            field=models.BooleanField(default=False),
        ),
    ]
