# Generated by Django 5.2.13 on 2026-08-30 21:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("ingestion", "0029_alter_providermatchevent_event_type"),
        ("ingestion", "0030_providermatchcarry"),
        ("ingestion", "0031_carry_continuity_and_classifications"),
        ("ingestion", "0032_conservative_carry_continuity"),
        ("ingestion", "0033_carry_confidence"),
        ("ingestion", "0034_match_game_state"),
        ("ingestion", "0034_game_state_foundations"),
        ("ingestion", "0035_possession_context"),
        ("ingestion", "0036_player_season_role"),
        ("ingestion", "0037_player_team_role_redesign"),
        ("ingestion", "0038_add_player_role_run_kind"),
    ]

    dependencies = [
        ("ingestion", "0028_providermatchevent_is_defensive"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermatchevent",
            name="away_score_after",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="away_score_before",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="dismissal_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("red", "Red card"),
                    ("second_yellow", "Second yellow"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="game_state_after",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Unknown"), (1, "Drawing"), (2, "Winning"), (3, "Losing")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="game_state_before",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Unknown"), (1, "Drawing"), (2, "Winning"), (3, "Losing")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="home_score_after",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="home_score_before",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="is_deleted_event",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="is_goal_disallowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="participation_action",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("substitution_on", "Substitution on"),
                    ("substitution_off", "Substitution off"),
                    ("player_on", "Player on"),
                    ("player_off", "Player off"),
                    ("player_retired", "Player retired"),
                    ("player_returns", "Player returns"),
                ],
                default="none",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="provider_event_sequence_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="related_provider_event_sequence_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="related_provider_player_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="scoring_provider_team_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="timeline_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingestionrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reep_sync", "Reep sync"),
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("sofascore_team", "Sofascore team"),
                    ("position_resolution", "Position resolution"),
                    ("merge", "Merge"),
                    ("team_merge", "Team merge"),
                    ("derived", "Derived stats"),
                    ("galaxy", "Galaxy embeddings"),
                    ("whoscored_fetch", "WhoScored fetch"),
                    ("event_profiles", "Event profiles"),
                    ("player_roles", "Player roles"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="providermatchevent",
            name="event_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Pass"),
                    (2, "Ball touch"),
                    (3, "Take-on"),
                    (4, "Shot"),
                    (5, "Ball recovery"),
                    (6, "Tackle"),
                    (7, "Interception"),
                    (8, "Clearance"),
                    (9, "Blocked pass"),
                    (10, "Aerial"),
                    (11, "Challenge"),
                    (12, "Dispossessed"),
                    (13, "Foul"),
                    (14, "Save"),
                    (15, "Offside"),
                    (16, "Card"),
                    (17, "Substitution"),
                    (18, "Administrative"),
                    (19, "Own goal"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="PlayerSeasonRoleFeatureSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_version", models.CharField(db_index=True, max_length=64)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("verified_exposure_seconds", models.PositiveIntegerField(default=0)),
                ("source_event_version", models.CharField(max_length=64)),
                ("source_state_version", models.CharField(max_length=64)),
                ("source_participation_version", models.CharField(max_length=64)),
                ("source_possession_version", models.CharField(max_length=64)),
                ("calculated_through_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calculated_through_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_role_features_calculated_through",
                        to="ingestion.providermatch",
                    ),
                ),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_role_feature_snapshots",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_feature_snapshots",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_role_feature_snapshots",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerSeasonRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_archetype",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("primary_fit", models.FloatField(blank=True, null=True)),
                (
                    "secondary_archetype",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("secondary_fit", models.FloatField(blank=True, null=True)),
                ("classification_shape", models.CharField(max_length=24)),
                ("evidence_confidence", models.CharField(max_length=24)),
                ("traits", models.JSONField(blank=True, default=list)),
                ("candidates", models.JSONField(blank=True, default=list)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("scoring_version", models.CharField(db_index=True, max_length=64)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_season_roles",
                        to="ingestion.competitionseason",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_roles",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_season_roles",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "feature_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classifications",
                        to="ingestion.playerseasonrolefeaturesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchCarry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_event_index", models.PositiveIntegerField()),
                ("end_event_index", models.PositiveIntegerField()),
                ("provider_team_id", models.CharField(max_length=64)),
                (
                    "provider_player_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "First half"),
                            (2, "Second half"),
                            (3, "First period of extra time"),
                            (4, "Second period of extra time"),
                            (5, "Penalty shootout"),
                            (6, "Post-game"),
                        ],
                        default=0,
                    ),
                ),
                ("minute", models.PositiveSmallIntegerField()),
                (
                    "second",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                ("match_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "end_x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "end_y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                ("is_progressive_carry", models.BooleanField(default=False)),
                ("is_final_third_entry", models.BooleanField(default=False)),
                ("is_box_entry", models.BooleanField(default=False)),
                ("is_low_confidence", models.BooleanField(default=False)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_carries",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_carries",
                        to="ingestion.providermatch",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_carries",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchGameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("verified_with_shootout", "Verified with shootout"),
                            ("unverified", "Unverified"),
                            ("no_events", "No events"),
                            ("score_mismatch", "Score mismatch"),
                            ("invalid", "Invalid"),
                        ],
                        default="unverified",
                        max_length=32,
                    ),
                ),
                ("eligible", models.BooleanField(default=False)),
                (
                    "exclusion_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_completed", "Match is not completed"),
                            ("non_final_payload", "Payload is not final"),
                            ("team_identity_unresolved", "Team identity unresolved"),
                            ("score_unavailable", "Score unavailable"),
                            ("score_mismatch", "Score mismatch"),
                            ("invalid_score_replay", "Invalid score replay"),
                            ("clock_metadata_missing", "Clock metadata missing"),
                            ("clock_metadata_invalid", "Clock metadata invalid"),
                            ("event_timestamp_invalid", "Event timestamp invalid"),
                            ("no_supported_play", "No supported play"),
                            ("abandoned_or_incomplete", "Abandoned or incomplete"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("calculation_version", models.CharField(max_length=64)),
                (
                    "source_checksum",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("goal_event_count", models.PositiveIntegerField(default=0)),
                ("ignored_goal_event_count", models.PositiveIntegerField(default=0)),
                ("shootout_goal_event_count", models.PositiveIntegerField(default=0)),
                (
                    "replayed_home_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "replayed_away_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "replayed_shootout_home_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "replayed_shootout_away_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "supported_start_second",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "supported_end_second",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("exposure_seconds", models.PositiveIntegerField(default=0)),
                ("period_count", models.PositiveSmallIntegerField(default=0)),
                ("episode_count", models.PositiveIntegerField(default=0)),
                ("focal_team_count", models.PositiveSmallIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField()),
                (
                    "provider_match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_state",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayedPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "First half"),
                            (2, "Second half"),
                            (3, "First period of extra time"),
                            (4, "Second period of extra time"),
                            (5, "Penalty shootout"),
                            (6, "Post-game"),
                        ]
                    ),
                ),
                ("period_index", models.PositiveSmallIntegerField()),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("calculation_version", models.CharField(max_length=64)),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_periods",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayerParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_team_id", models.CharField(max_length=64)),
                ("provider_player_id", models.CharField(max_length=64)),
                (
                    "roster_role",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("substitute", "Substitute"),
                            ("added", "Added from event evidence"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "position_role",
                    models.CharField(
                        choices=[
                            ("goalkeeper", "Goalkeeper"),
                            ("outfield", "Outfield"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partial", "Partial"),
                            ("excluded", "Excluded"),
                            ("unused", "Unused substitute"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partial", "Partial"),
                            ("unverified", "Unverified"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "exclusion_reason",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("on_pitch_seconds", models.PositiveIntegerField(default=0)),
                ("excluded_seconds", models.PositiveIntegerField(default=0)),
                ("interval_count", models.PositiveSmallIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_participations",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_participations",
                        to="ingestion.providermatch",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_participations",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayerInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "start_evidence",
                    models.CharField(
                        choices=[
                            ("lineup_starter", "Lineup starter"),
                            ("substitution_on", "Substitution on"),
                            ("player_on", "Player on"),
                            ("player_returns", "Player returns"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "end_evidence",
                    models.CharField(
                        choices=[
                            ("substitution_off", "Substitution off"),
                            ("player_off", "Player off"),
                            ("player_retired", "Player retired"),
                            ("dismissal_red", "Red-card dismissal"),
                            ("dismissal_second_yellow", "Second-yellow dismissal"),
                            ("match_end", "Match end"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "start_event_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("end_event_index", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "start_event_sequence_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "end_event_sequence_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partial", "Partial"),
                            ("unverified", "Unverified"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "exclusion_reason",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervals",
                        to="ingestion.providermatchplayerparticipation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayerParticipationBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partial", "Partial"),
                            ("excluded", "Excluded"),
                            ("no_lineup", "No lineup"),
                        ],
                        default="excluded",
                        max_length=16,
                    ),
                ),
                ("formula_version", models.CharField(max_length=64)),
                (
                    "source_payload_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "match_clock_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "team_episode_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("participant_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "verified_participant_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "excluded_participant_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("unused_player_count", models.PositiveSmallIntegerField(default=0)),
                ("interval_count", models.PositiveSmallIntegerField(default=0)),
                ("verified_seconds", models.PositiveIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField()),
                (
                    "provider_match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_participation_build",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="providermatchplayerparticipation",
            name="build",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="ingestion.providermatchplayerparticipationbuild",
            ),
        ),
        migrations.CreateModel(
            name="ProviderMatchPossessionBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculation_version", models.CharField(max_length=64)),
                (
                    "source_checksum",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("possession_count", models.PositiveIntegerField(default=0)),
                ("included_event_count", models.PositiveIntegerField(default=0)),
                ("excluded_event_count", models.PositiveIntegerField(default=0)),
                ("ambiguous_event_count", models.PositiveIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField()),
                (
                    "provider_match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possession_build",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPossession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("possession_index", models.PositiveIntegerField()),
                ("identity", models.CharField(max_length=160)),
                ("provider_team_id", models.CharField(max_length=64)),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "First half"),
                            (2, "Second half"),
                            (3, "First period of extra time"),
                            (4, "Second period of extra time"),
                            (5, "Penalty shootout"),
                            (6, "Post-game"),
                        ]
                    ),
                ),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "start_x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "start_y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "end_x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "end_y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                ("action_count", models.PositiveIntegerField()),
                ("termination_reason", models.CharField(max_length=32)),
                ("launch_type", models.CharField(max_length=32)),
                ("is_ambiguous", models.BooleanField(default=False)),
                (
                    "exclusion_reason",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "establishment_second",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "establishment_event_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_settled", models.BooleanField(default=False)),
                ("is_counter_launch", models.BooleanField(default=False)),
                ("counter_final_third_arrival", models.BooleanField(default=False)),
                ("counter_box_arrival", models.BooleanField(default=False)),
                ("counter_shot", models.BooleanField(default=False)),
                (
                    "counter_outcome",
                    models.CharField(blank=True, max_length=24, null=True),
                ),
                (
                    "counter_elapsed_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "counter_forward_metres",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "counter_speed_mps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "provider_fast_break_shot_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "settled_defensive_action_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "settled_defensive_average_x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "settled_block_height",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("state_segments", models.JSONField(blank=True, default=list)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possessions",
                        to="ingestion.providermatch",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_possessions",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possessions",
                        to="ingestion.providermatchpossessionbuild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPossessionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("is_control_action", models.BooleanField(default=False)),
                ("is_settled_defensive_action", models.BooleanField(default=False)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possession_link",
                        to="ingestion.providermatchevent",
                    ),
                ),
                (
                    "possession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_links",
                        to="ingestion.providermatchpossession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPossessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_player_id", models.CharField(max_length=64)),
                ("first_event_index", models.PositiveIntegerField()),
                ("action_count", models.PositiveSmallIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_possessions",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "possession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="ingestion.providermatchpossession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchTeamGameStateEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("focal_is_home", models.BooleanField()),
                ("episode_index", models.PositiveSmallIntegerField()),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "First half"),
                            (2, "Second half"),
                            (3, "First period of extra time"),
                            (4, "Second period of extra time"),
                            (5, "Penalty shootout"),
                            (6, "Post-game"),
                        ]
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("first_half", "First half"),
                            ("second_half", "Second half"),
                            ("first_extra_time", "First period of extra time"),
                            ("second_extra_time", "Second period of extra time"),
                        ],
                        max_length=24,
                    ),
                ),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("is_added_time", models.BooleanField(default=False)),
                ("focal_score", models.PositiveSmallIntegerField()),
                ("opponent_score", models.PositiveSmallIntegerField()),
                ("goal_difference", models.SmallIntegerField()),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Drawing"),
                            (2, "Winning"),
                            (3, "Losing"),
                        ]
                    ),
                ),
                (
                    "previous_state",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Unknown"),
                            (1, "Drawing"),
                            (2, "Winning"),
                            (3, "Losing"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "draw_provenance",
                    models.CharField(
                        choices=[
                            ("none", "Not a draw"),
                            ("neutral", "Neutral draw"),
                            ("restored", "Restored draw"),
                            ("surrendered", "Surrendered draw"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("state_entry_second", models.PositiveIntegerField()),
                ("state_age_seconds_at_start", models.PositiveIntegerField()),
                (
                    "entry_event_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("calculation_version", models.CharField(max_length=64)),
                (
                    "entry_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_game_state_episodes",
                        to="ingestion.providermatchevent",
                    ),
                ),
                (
                    "focal_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="game_state_episodes",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_game_state_episodes",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayerStateExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "coarse_state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Drawing"),
                            (2, "Winning"),
                            (3, "Losing"),
                        ]
                    ),
                ),
                ("goal_difference", models.SmallIntegerField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("first_half", "First half"),
                            ("second_half", "Second half"),
                            ("first_extra_time", "First period of extra time"),
                            ("second_extra_time", "Second period of extra time"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("none", "Not a draw"),
                            ("neutral", "Neutral draw"),
                            ("restored", "Restored draw"),
                            ("surrendered", "Surrendered draw"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("state_age_bucket", models.CharField(max_length=24)),
                ("state_age_start_seconds", models.PositiveIntegerField()),
                ("state_age_end_seconds", models.PositiveIntegerField()),
                ("formula_version", models.CharField(max_length=64)),
                (
                    "player_interval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_exposures",
                        to="ingestion.providermatchplayerinterval",
                    ),
                ),
                (
                    "team_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_state_exposures",
                        to="ingestion.providermatchteamgamestateepisode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchTeamGameStateExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Drawing"),
                            (2, "Winning"),
                            (3, "Losing"),
                        ]
                    ),
                ),
                ("goal_difference", models.SmallIntegerField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("first_half", "First half"),
                            ("second_half", "Second half"),
                            ("first_extra_time", "First period of extra time"),
                            ("second_extra_time", "Second period of extra time"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "draw_provenance",
                    models.CharField(
                        choices=[
                            ("none", "Not a draw"),
                            ("neutral", "Neutral draw"),
                            ("restored", "Restored draw"),
                            ("surrendered", "Surrendered draw"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("exposure_seconds", models.PositiveIntegerField()),
                ("episode_count", models.PositiveSmallIntegerField()),
                ("calculation_version", models.CharField(max_length=64)),
                (
                    "focal_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="game_state_exposures",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_game_state_exposures",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="playerseasonrolefeaturesnapshot",
            index=models.Index(
                fields=["competition_season", "team", "player", "is_current"],
                name="player_role_feature_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerseasonrolefeaturesnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("competition_season", "player", "team"),
                name="uniq_current_role_feature",
            ),
        ),
        migrations.AddIndex(
            model_name="playerseasonrole",
            index=models.Index(
                fields=["competition_season", "team", "player", "is_current"],
                name="player_team_role_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playerseasonrole",
            index=models.Index(
                fields=["competition_season", "primary_archetype", "is_current"],
                name="primary_archetype_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerseasonrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("competition_season", "player", "team"),
                name="uniq_current_player_team_role",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchcarry",
            index=models.Index(
                fields=["player", "provider_match"], name="prov_carry_player_match_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchcarry",
            index=models.Index(
                fields=["team", "provider_match"], name="prov_carry_team_match_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchcarry",
            constraint=models.UniqueConstraint(
                fields=("provider_match", "start_event_index"),
                name="uniq_provider_match_carry",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchcarry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("x__isnull", True),
                        models.Q(("x__gte", 0), ("x__lte", 10000)),
                        _connector="OR",
                    ),
                    models.Q(
                        ("y__isnull", True),
                        models.Q(("y__gte", 0), ("y__lte", 10000)),
                        _connector="OR",
                    ),
                    models.Q(
                        ("end_x__isnull", True),
                        models.Q(("end_x__gte", 0), ("end_x__lte", 10000)),
                        _connector="OR",
                    ),
                    models.Q(
                        ("end_y__isnull", True),
                        models.Q(("end_y__gte", 0), ("end_y__lte", 10000)),
                        _connector="OR",
                    ),
                    ("second__gte", 0),
                    ("second__lte", 59),
                ),
                name="provider_carry_coords_range",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchgamestate",
            index=models.Index(
                fields=["status", "calculated_at"], name="prov_match_game_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchplayedperiod",
            index=models.Index(
                fields=["provider_match", "period_index"],
                name="played_period_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayedperiod",
            constraint=models.UniqueConstraint(
                fields=("provider_match", "period"), name="uniq_match_played_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayedperiod",
            constraint=models.UniqueConstraint(
                fields=("provider_match", "period_index"),
                name="uniq_match_period_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayedperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_second__gt", models.F("start_second"))),
                name="played_period_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerinterval",
            constraint=models.UniqueConstraint(
                fields=("participation", "sequence"),
                name="uniq_player_interval_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerinterval",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_second__gt", models.F("start_second"))),
                name="player_interval_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchplayerparticipation",
            index=models.Index(
                fields=["player", "team", "status"],
                name="player_participation_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerparticipation",
            constraint=models.UniqueConstraint(
                fields=("build", "provider_team_id", "provider_player_id"),
                name="uniq_match_player_participation",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchpossession",
            index=models.Index(
                fields=["team", "is_counter_launch"], name="possession_team_counter_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchpossession",
            index=models.Index(
                fields=["provider_match", "period", "start_second"],
                name="possession_match_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchpossession",
            constraint=models.UniqueConstraint(
                fields=("provider_match", "possession_index"),
                name="uniq_match_possession_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchpossession",
            constraint=models.UniqueConstraint(
                fields=("provider_match", "identity"),
                name="uniq_match_possession_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchpossessionevent",
            constraint=models.UniqueConstraint(
                fields=("possession", "sequence"), name="uniq_possession_event_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchpossessionparticipant",
            constraint=models.UniqueConstraint(
                fields=("possession", "provider_player_id"),
                name="uniq_possession_participant",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchteamgamestateepisode",
            index=models.Index(
                fields=["provider_match", "focal_team", "start_second", "end_second"],
                name="team_state_episode_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchteamgamestateepisode",
            index=models.Index(
                fields=["focal_team", "state", "phase"], name="team_state_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateepisode",
            constraint=models.UniqueConstraint(
                fields=("provider_match", "focal_team", "episode_index"),
                name="uniq_match_team_state_episode",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateepisode",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_second__gt", models.F("start_second"))),
                name="state_episode_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateepisode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state_entry_second__lte", models.F("start_second"))
                ),
                name="state_entry_before_episode",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchplayerstateexposure",
            index=models.Index(
                fields=["coarse_state", "phase", "provenance"],
                name="player_state_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerstateexposure",
            constraint=models.UniqueConstraint(
                fields=(
                    "player_interval",
                    "team_episode",
                    "start_second",
                    "end_second",
                ),
                name="uniq_player_state_exposure",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerstateexposure",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_second__gt", models.F("start_second"))),
                name="player_state_exposure_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchteamgamestateexposure",
            index=models.Index(
                fields=["focal_team", "state", "phase"], name="team_state_exposure_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateexposure",
            constraint=models.UniqueConstraint(
                fields=(
                    "provider_match",
                    "focal_team",
                    "state",
                    "goal_difference",
                    "phase",
                    "draw_provenance",
                ),
                name="uniq_match_team_state_exposure",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateexposure",
            constraint=models.CheckConstraint(
                condition=models.Q(("exposure_seconds__gt", 0)),
                name="team_state_exposure_positive",
            ),
        ),
    ]
