# Generated by Django 5.1.7 on 2026-08-21 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0029_alter_providermatchevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderMatchCarry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_event_index", models.PositiveIntegerField()),
                ("end_event_index", models.PositiveIntegerField()),
                ("provider_team_id", models.CharField(max_length=64)),
                (
                    "provider_player_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "First half"),
                            (2, "Second half"),
                            (3, "First period of extra time"),
                            (4, "Second period of extra time"),
                            (5, "Penalty shootout"),
                            (6, "Post-game"),
                        ],
                        default=0,
                    ),
                ),
                ("minute", models.PositiveSmallIntegerField()),
                (
                    "second",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                ("match_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "end_x",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "end_y",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_carries",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_carries",
                        to="ingestion.providermatch",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_carries",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player", "provider_match"],
                        name="prov_carry_player_match_idx",
                    ),
                    models.Index(
                        fields=["team", "provider_match"],
                        name="prov_carry_team_match_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_match", "start_event_index"),
                        name="uniq_provider_match_carry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("x__isnull", True),
                                models.Q(("x__gte", 0), ("x__lte", 10000)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("y__isnull", True),
                                models.Q(("y__gte", 0), ("y__lte", 10000)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("end_x__isnull", True),
                                models.Q(("end_x__gte", 0), ("end_x__lte", 10000)),
                                _connector="OR",
                            ),
                            models.Q(
                                ("end_y__isnull", True),
                                models.Q(("end_y__gte", 0), ("end_y__lte", 10000)),
                                _connector="OR",
                            ),
                            ("second__gte", 0),
                            ("second__lte", 59),
                        ),
                        name="provider_carry_coords_range",
                    ),
                ],
            },
        ),
    ]
