# Generated by Django 5.2.13 on 2026-08-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0034_match_game_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermatchevent",
            name="dismissal_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("red", "Red card"),
                    ("second_yellow", "Second yellow"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="participation_action",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("substitution_on", "Substitution on"),
                    ("substitution_off", "Substitution off"),
                    ("player_on", "Player on"),
                    ("player_off", "Player off"),
                    ("player_retired", "Player retired"),
                    ("player_returns", "Player returns"),
                ],
                default="none",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="provider_event_sequence_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="related_provider_event_sequence_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="related_provider_player_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="timeline_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayerParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_team_id", models.CharField(max_length=64)),
                ("provider_player_id", models.CharField(max_length=64)),
                (
                    "roster_role",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("substitute", "Substitute"),
                            ("added", "Added from event evidence"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "position_role",
                    models.CharField(
                        choices=[
                            ("goalkeeper", "Goalkeeper"),
                            ("outfield", "Outfield"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partial", "Partial"),
                            ("excluded", "Excluded"),
                            ("unused", "Unused substitute"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partial", "Partial"),
                            ("unverified", "Unverified"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "exclusion_reason",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("on_pitch_seconds", models.PositiveIntegerField(default=0)),
                ("excluded_seconds", models.PositiveIntegerField(default=0)),
                ("interval_count", models.PositiveSmallIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_participations",
                        to="ingestion.canonicalplayer",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_participations",
                        to="ingestion.providermatch",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_match_participations",
                        to="ingestion.canonicalteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayerInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "start_evidence",
                    models.CharField(
                        choices=[
                            ("lineup_starter", "Lineup starter"),
                            ("substitution_on", "Substitution on"),
                            ("player_on", "Player on"),
                            ("player_returns", "Player returns"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "end_evidence",
                    models.CharField(
                        choices=[
                            ("substitution_off", "Substitution off"),
                            ("player_off", "Player off"),
                            ("player_retired", "Player retired"),
                            ("dismissal_red", "Red-card dismissal"),
                            ("dismissal_second_yellow", "Second-yellow dismissal"),
                            ("match_end", "Match end"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "start_event_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("end_event_index", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "start_event_sequence_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "end_event_sequence_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partial", "Partial"),
                            ("unverified", "Unverified"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "exclusion_reason",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervals",
                        to="ingestion.providermatchplayerparticipation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayerParticipationBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("partial", "Partial"),
                            ("excluded", "Excluded"),
                            ("no_lineup", "No lineup"),
                        ],
                        default="excluded",
                        max_length=16,
                    ),
                ),
                ("formula_version", models.CharField(max_length=64)),
                (
                    "source_payload_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "match_clock_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "team_episode_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("participant_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "verified_participant_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "excluded_participant_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("unused_player_count", models.PositiveSmallIntegerField(default=0)),
                ("interval_count", models.PositiveSmallIntegerField(default=0)),
                ("verified_seconds", models.PositiveIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField()),
                (
                    "provider_match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_participation_build",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="providermatchplayerparticipation",
            name="build",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="ingestion.providermatchplayerparticipationbuild",
            ),
        ),
        migrations.CreateModel(
            name="ProviderMatchTeamGameStateEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("focal_is_home", models.BooleanField()),
                ("episode_index", models.PositiveSmallIntegerField()),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "First half"),
                            (2, "Second half"),
                            (3, "First period of extra time"),
                            (4, "Second period of extra time"),
                            (5, "Penalty shootout"),
                            (6, "Post-game"),
                        ]
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("first_half", "First half"),
                            ("second_half", "Second half"),
                            ("first_extra_time", "First period of extra time"),
                            ("second_extra_time", "Second period of extra time"),
                        ],
                        max_length=24,
                    ),
                ),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("is_added_time", models.BooleanField(default=False)),
                ("focal_score", models.PositiveSmallIntegerField()),
                ("opponent_score", models.PositiveSmallIntegerField()),
                ("goal_difference", models.SmallIntegerField()),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Drawing"),
                            (2, "Winning"),
                            (3, "Losing"),
                        ]
                    ),
                ),
                (
                    "previous_state",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Unknown"),
                            (1, "Drawing"),
                            (2, "Winning"),
                            (3, "Losing"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "draw_provenance",
                    models.CharField(
                        choices=[
                            ("none", "Not a draw"),
                            ("neutral", "Neutral draw"),
                            ("restored", "Restored draw"),
                            ("surrendered", "Surrendered draw"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("state_entry_second", models.PositiveIntegerField()),
                ("state_age_seconds_at_start", models.PositiveIntegerField()),
                (
                    "entry_event_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("calculation_version", models.CharField(max_length=64)),
                (
                    "entry_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_game_state_episodes",
                        to="ingestion.providermatchevent",
                    ),
                ),
                (
                    "focal_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="game_state_episodes",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_game_state_episodes",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayerStateExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "coarse_state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Drawing"),
                            (2, "Winning"),
                            (3, "Losing"),
                        ]
                    ),
                ),
                ("goal_difference", models.SmallIntegerField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("first_half", "First half"),
                            ("second_half", "Second half"),
                            ("first_extra_time", "First period of extra time"),
                            ("second_extra_time", "Second period of extra time"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("none", "Not a draw"),
                            ("neutral", "Neutral draw"),
                            ("restored", "Restored draw"),
                            ("surrendered", "Surrendered draw"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("state_age_bucket", models.CharField(max_length=24)),
                ("state_age_start_seconds", models.PositiveIntegerField()),
                ("state_age_end_seconds", models.PositiveIntegerField()),
                ("formula_version", models.CharField(max_length=64)),
                (
                    "player_interval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_exposures",
                        to="ingestion.providermatchplayerinterval",
                    ),
                ),
                (
                    "team_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_state_exposures",
                        to="ingestion.providermatchteamgamestateepisode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchTeamGameStateExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Drawing"),
                            (2, "Winning"),
                            (3, "Losing"),
                        ]
                    ),
                ),
                ("goal_difference", models.SmallIntegerField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("first_half", "First half"),
                            ("second_half", "Second half"),
                            ("first_extra_time", "First period of extra time"),
                            ("second_extra_time", "Second period of extra time"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "draw_provenance",
                    models.CharField(
                        choices=[
                            ("none", "Not a draw"),
                            ("neutral", "Neutral draw"),
                            ("restored", "Restored draw"),
                            ("surrendered", "Surrendered draw"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("exposure_seconds", models.PositiveIntegerField()),
                ("episode_count", models.PositiveSmallIntegerField()),
                ("calculation_version", models.CharField(max_length=64)),
                (
                    "focal_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="game_state_exposures",
                        to="ingestion.canonicalteam",
                    ),
                ),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_game_state_exposures",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="exclusion_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_completed", "Match is not completed"),
                    ("non_final_payload", "Payload is not final"),
                    ("team_identity_unresolved", "Team identity unresolved"),
                    ("score_unavailable", "Score unavailable"),
                    ("score_mismatch", "Score mismatch"),
                    ("invalid_score_replay", "Invalid score replay"),
                    ("clock_metadata_missing", "Clock metadata missing"),
                    ("clock_metadata_invalid", "Clock metadata invalid"),
                    ("event_timestamp_invalid", "Event timestamp invalid"),
                    ("no_supported_play", "No supported play"),
                    ("abandoned_or_incomplete", "Abandoned or incomplete"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="source_checksum",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="supported_start_second",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="supported_end_second",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="exposure_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="period_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="episode_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="providermatchgamestate",
            name="focal_team_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProviderMatchPlayedPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "First half"),
                            (2, "Second half"),
                            (3, "First period of extra time"),
                            (4, "Second period of extra time"),
                            (5, "Penalty shootout"),
                            (6, "Post-game"),
                        ]
                    ),
                ),
                ("period_index", models.PositiveSmallIntegerField()),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("calculation_version", models.CharField(max_length=64)),
                (
                    "provider_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="played_periods",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider_match", "period_index"],
                        name="played_period_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_match", "period"),
                        name="uniq_match_played_period",
                    ),
                    models.UniqueConstraint(
                        fields=("provider_match", "period_index"),
                        name="uniq_match_period_index",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_second__gt", models.F("start_second"))
                        ),
                        name="played_period_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerinterval",
            constraint=models.UniqueConstraint(
                fields=("participation", "sequence"),
                name="uniq_player_interval_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerinterval",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_second__gt", models.F("start_second"))),
                name="player_interval_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchplayerparticipation",
            index=models.Index(
                fields=["player", "team", "status"],
                name="player_participation_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerparticipation",
            constraint=models.UniqueConstraint(
                fields=("build", "provider_team_id", "provider_player_id"),
                name="uniq_match_player_participation",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchteamgamestateepisode",
            index=models.Index(
                fields=["provider_match", "focal_team", "start_second", "end_second"],
                name="team_state_episode_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchteamgamestateepisode",
            index=models.Index(
                fields=["focal_team", "state", "phase"], name="team_state_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateepisode",
            constraint=models.UniqueConstraint(
                fields=("provider_match", "focal_team", "episode_index"),
                name="uniq_match_team_state_episode",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateepisode",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_second__gt", models.F("start_second"))),
                name="state_episode_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateepisode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state_entry_second__lte", models.F("start_second"))
                ),
                name="state_entry_before_episode",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchplayerstateexposure",
            index=models.Index(
                fields=["coarse_state", "phase", "provenance"],
                name="player_state_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerstateexposure",
            constraint=models.UniqueConstraint(
                fields=(
                    "player_interval",
                    "team_episode",
                    "start_second",
                    "end_second",
                ),
                name="uniq_player_state_exposure",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchplayerstateexposure",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_second__gt", models.F("start_second"))),
                name="player_state_exposure_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="providermatchteamgamestateexposure",
            index=models.Index(
                fields=["focal_team", "state", "phase"], name="team_state_exposure_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateexposure",
            constraint=models.UniqueConstraint(
                fields=(
                    "provider_match",
                    "focal_team",
                    "state",
                    "goal_difference",
                    "phase",
                    "draw_provenance",
                ),
                name="uniq_match_team_state_exposure",
            ),
        ),
        migrations.AddConstraint(
            model_name="providermatchteamgamestateexposure",
            constraint=models.CheckConstraint(
                condition=models.Q(("exposure_seconds__gt", 0)),
                name="team_state_exposure_positive",
            ),
        ),
    ]
