# Generated by Django 5.2.13 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0033_carry_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="providermatchevent",
            name="is_goal_disallowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="is_deleted_event",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="scoring_provider_team_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="home_score_before",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="away_score_before",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="home_score_after",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="away_score_after",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="game_state_before",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Unknown"), (1, "Drawing"), (2, "Winning"), (3, "Losing")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="providermatchevent",
            name="game_state_after",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Unknown"), (1, "Drawing"), (2, "Winning"), (3, "Losing")],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProviderMatchGameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("verified_with_shootout", "Verified with shootout"),
                            ("unverified", "Unverified"),
                            ("no_events", "No events"),
                            ("score_mismatch", "Score mismatch"),
                            ("invalid", "Invalid"),
                        ],
                        default="unverified",
                        max_length=32,
                    ),
                ),
                ("calculation_version", models.CharField(max_length=64)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("goal_event_count", models.PositiveIntegerField(default=0)),
                ("ignored_goal_event_count", models.PositiveIntegerField(default=0)),
                ("shootout_goal_event_count", models.PositiveIntegerField(default=0)),
                (
                    "replayed_home_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "replayed_away_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "replayed_shootout_home_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "replayed_shootout_away_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField()),
                (
                    "provider_match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_state",
                        to="ingestion.providermatch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "calculated_at"],
                        name="prov_match_game_state_idx",
                    )
                ],
            },
        ),
    ]
