# Generated by Django 5.2 on 2026-08-23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


coordinate = dict(
    blank=True,
    null=True,
    validators=[
        django.core.validators.MinValueValidator(0),
        django.core.validators.MaxValueValidator(10000),
    ],
)


class Migration(migrations.Migration):
    dependencies = [("ingestion", "0034_game_state_foundations")]

    operations = [
        migrations.CreateModel(
            name="ProviderMatchPossessionBuild",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calculation_version", models.CharField(max_length=64)),
                ("source_checksum", models.CharField(blank=True, default="", max_length=64)),
                ("possession_count", models.PositiveIntegerField(default=0)),
                ("included_event_count", models.PositiveIntegerField(default=0)),
                ("excluded_event_count", models.PositiveIntegerField(default=0)),
                ("ambiguous_event_count", models.PositiveIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField()),
                ("provider_match", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="possession_build", to="ingestion.providermatch")),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPossession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("possession_index", models.PositiveIntegerField()),
                ("identity", models.CharField(max_length=160)),
                ("provider_team_id", models.CharField(max_length=64)),
                ("period", models.PositiveSmallIntegerField(choices=[(0, "Unknown"), (1, "First half"), (2, "Second half"), (3, "First period of extra time"), (4, "Second period of extra time"), (5, "Penalty shootout"), (6, "Post-game")])),
                ("start_second", models.PositiveIntegerField()),
                ("end_second", models.PositiveIntegerField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("start_x", models.PositiveSmallIntegerField(**coordinate)),
                ("start_y", models.PositiveSmallIntegerField(**coordinate)),
                ("end_x", models.PositiveSmallIntegerField(**coordinate)),
                ("end_y", models.PositiveSmallIntegerField(**coordinate)),
                ("action_count", models.PositiveIntegerField()),
                ("termination_reason", models.CharField(max_length=32)),
                ("launch_type", models.CharField(max_length=32)),
                ("is_ambiguous", models.BooleanField(default=False)),
                ("exclusion_reason", models.CharField(blank=True, max_length=64, null=True)),
                ("establishment_second", models.PositiveIntegerField(blank=True, null=True)),
                ("establishment_event_index", models.PositiveIntegerField(blank=True, null=True)),
                ("is_settled", models.BooleanField(default=False)),
                ("is_counter_launch", models.BooleanField(default=False)),
                ("counter_final_third_arrival", models.BooleanField(default=False)),
                ("counter_box_arrival", models.BooleanField(default=False)),
                ("counter_shot", models.BooleanField(default=False)),
                ("counter_outcome", models.CharField(blank=True, max_length=24, null=True)),
                ("counter_elapsed_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("counter_forward_metres", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("counter_speed_mps", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("provider_fast_break_shot_count", models.PositiveSmallIntegerField(default=0)),
                ("settled_defensive_action_count", models.PositiveSmallIntegerField(default=0)),
                ("settled_defensive_average_x", models.PositiveSmallIntegerField(**coordinate)),
                ("settled_block_height", models.CharField(blank=True, max_length=8, null=True)),
                ("state_segments", models.JSONField(blank=True, default=list)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("build", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="possessions", to="ingestion.providermatchpossessionbuild")),
                ("provider_match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="possessions", to="ingestion.providermatch")),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="provider_match_possessions", to="ingestion.canonicalteam")),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPossessionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveSmallIntegerField()),
                ("is_control_action", models.BooleanField(default=False)),
                ("is_settled_defensive_action", models.BooleanField(default=False)),
                ("event", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="possession_link", to="ingestion.providermatchevent")),
                ("possession", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_links", to="ingestion.providermatchpossession")),
            ],
        ),
        migrations.CreateModel(
            name="ProviderMatchPossessionParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_player_id", models.CharField(max_length=64)),
                ("first_event_index", models.PositiveIntegerField()),
                ("action_count", models.PositiveSmallIntegerField()),
                ("player", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="provider_match_possessions", to="ingestion.canonicalplayer")),
                ("possession", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="ingestion.providermatchpossession")),
            ],
        ),
        migrations.AddIndex(model_name="providermatchpossession", index=models.Index(fields=["team", "is_counter_launch"], name="possession_team_counter_idx")),
        migrations.AddIndex(model_name="providermatchpossession", index=models.Index(fields=["provider_match", "period", "start_second"], name="possession_match_time_idx")),
        migrations.AddConstraint(model_name="providermatchpossession", constraint=models.UniqueConstraint(fields=("provider_match", "possession_index"), name="uniq_match_possession_index")),
        migrations.AddConstraint(model_name="providermatchpossession", constraint=models.UniqueConstraint(fields=("provider_match", "identity"), name="uniq_match_possession_identity")),
        migrations.AddConstraint(model_name="providermatchpossessionevent", constraint=models.UniqueConstraint(fields=("possession", "sequence"), name="uniq_possession_event_sequence")),
        migrations.AddConstraint(model_name="providermatchpossessionparticipant", constraint=models.UniqueConstraint(fields=("possession", "provider_player_id"), name="uniq_possession_participant")),
    ]
