# Generated by Django 5.2.13 on 2026-08-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0037_player_team_role_redesign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reep_sync", "Reep sync"),
                    ("understat", "Understat"),
                    ("sofascore", "Sofascore"),
                    ("sofascore_team", "Sofascore team"),
                    ("position_resolution", "Position resolution"),
                    ("merge", "Merge"),
                    ("team_merge", "Team merge"),
                    ("derived", "Derived stats"),
                    ("galaxy", "Galaxy embeddings"),
                    ("whoscored_fetch", "WhoScored fetch"),
                    ("event_profiles", "Event profiles"),
                    ("player_roles", "Player roles"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
