# Generated by Django 5.1.15 on 2026-08-10

import django.db.models.deletion
import editorial.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(default="Untitled analysis", max_length=180)),
                ("subtitle", models.CharField(blank=True, max_length=280)),
                ("status", models.CharField(choices=[("draft", "Draft")], default="draft", max_length=20)),
                ("document", models.JSONField(default=editorial.models.empty_document)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("preview_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("preview_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="editorial_articles", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=180)),
                ("subtitle", models.CharField(blank=True, max_length=280)),
                ("document", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="editorial.article")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="editorial_revisions_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-number",),
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["author", "status", "-updated_at"], name="editorial_author_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="articlerevision",
            constraint=models.UniqueConstraint(fields=("article", "number"), name="unique_editorial_article_revision"),
        ),
    ]
