from __future__ import annotations

from ingestion.models import PlayerDataMode

SEASON_LABELS = (
    "2021-22",
    "2022-23",
    "2023-24",
    "2024-25",
    "2025-26",
)


def _sort_order(label: str) -> int:
    return int(label.split("-")[1])


def _season_row(
    label: str,
    *,
    sofascore_unique_tournament_id: int | None,
    sofascore_season_id: int | None,
    understat_league: str | None = None,
    understat_season_year: str | None = None,
    is_active: bool = True,
    refresh_enabled: bool = False,
) -> dict:
    return {
        "label": label,
        "sort_order": _sort_order(label),
        "sofascore_unique_tournament_id": sofascore_unique_tournament_id,
        "sofascore_season_id": sofascore_season_id,
        "understat_league": understat_league,
        "understat_season_year": understat_season_year,
        "is_active": is_active,
        "refresh_enabled": refresh_enabled,
    }


COMPETITION_SEED_MANIFEST = [
    {
        "code": "ENG1",
        "aliases": ["EPL"],
        "name": "Premier League",
        "country": "England",
        "player_data_mode": PlayerDataMode.FULL_MERGE,
        "has_understat": True,
        "has_sofascore": True,
        "expected_team_count": 20,
        "min_merged_team_count": 18,
        "min_team_stats_coverage_count": 18,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=17, sofascore_season_id=37036, understat_league="EPL", understat_season_year="2021"),
            _season_row("2022-23", sofascore_unique_tournament_id=17, sofascore_season_id=41886, understat_league="EPL", understat_season_year="2022"),
            _season_row("2023-24", sofascore_unique_tournament_id=17, sofascore_season_id=52186, understat_league="EPL", understat_season_year="2023"),
            _season_row("2024-25", sofascore_unique_tournament_id=17, sofascore_season_id=61627, understat_league="EPL", understat_season_year="2024"),
            _season_row("2025-26", sofascore_unique_tournament_id=17, sofascore_season_id=76986, understat_league="EPL", understat_season_year="2025", refresh_enabled=True),
        ],
    },
    {
        "code": "ITA1",
        "name": "Serie A",
        "country": "Italy",
        "player_data_mode": PlayerDataMode.FULL_MERGE,
        "has_understat": True,
        "has_sofascore": True,
        "expected_team_count": 20,
        "min_merged_team_count": 18,
        "min_team_stats_coverage_count": 18,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=23, sofascore_season_id=37475, understat_league="Serie_A", understat_season_year="2021"),
            _season_row("2022-23", sofascore_unique_tournament_id=23, sofascore_season_id=42415, understat_league="Serie_A", understat_season_year="2022"),
            _season_row("2023-24", sofascore_unique_tournament_id=23, sofascore_season_id=52760, understat_league="Serie_A", understat_season_year="2023"),
            _season_row("2024-25", sofascore_unique_tournament_id=23, sofascore_season_id=63515, understat_league="Serie_A", understat_season_year="2024"),
            _season_row("2025-26", sofascore_unique_tournament_id=23, sofascore_season_id=76457, understat_league="Serie_A", understat_season_year="2025", refresh_enabled=True),
        ],
    },
    {
        "code": "SPA1",
        "name": "La Liga",
        "country": "Spain",
        "player_data_mode": PlayerDataMode.FULL_MERGE,
        "has_understat": True,
        "has_sofascore": True,
        "expected_team_count": 20,
        "min_merged_team_count": 18,
        "min_team_stats_coverage_count": 18,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=8, sofascore_season_id=37223, understat_league="La_liga", understat_season_year="2021"),
            _season_row("2022-23", sofascore_unique_tournament_id=8, sofascore_season_id=42409, understat_league="La_liga", understat_season_year="2022"),
            _season_row("2023-24", sofascore_unique_tournament_id=8, sofascore_season_id=52376, understat_league="La_liga", understat_season_year="2023"),
            _season_row("2024-25", sofascore_unique_tournament_id=8, sofascore_season_id=61643, understat_league="La_liga", understat_season_year="2024"),
            _season_row("2025-26", sofascore_unique_tournament_id=8, sofascore_season_id=77559, understat_league="La_liga", understat_season_year="2025", refresh_enabled=True),
        ],
    },
    {
        "code": "GER1",
        "name": "Bundesliga",
        "country": "Germany",
        "player_data_mode": PlayerDataMode.FULL_MERGE,
        "has_understat": True,
        "has_sofascore": True,
        "expected_team_count": 18,
        "min_merged_team_count": 16,
        "min_team_stats_coverage_count": 16,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=35, sofascore_season_id=37166, understat_league="Bundesliga", understat_season_year="2021"),
            _season_row("2022-23", sofascore_unique_tournament_id=35, sofascore_season_id=42268, understat_league="Bundesliga", understat_season_year="2022"),
            _season_row("2023-24", sofascore_unique_tournament_id=35, sofascore_season_id=52608, understat_league="Bundesliga", understat_season_year="2023"),
            _season_row("2024-25", sofascore_unique_tournament_id=35, sofascore_season_id=63516, understat_league="Bundesliga", understat_season_year="2024"),
            _season_row("2025-26", sofascore_unique_tournament_id=35, sofascore_season_id=77333, understat_league="Bundesliga", understat_season_year="2025", refresh_enabled=True),
        ],
    },
    {
        "code": "FRA1",
        "name": "Ligue 1",
        "country": "France",
        "player_data_mode": PlayerDataMode.FULL_MERGE,
        "has_understat": True,
        "has_sofascore": True,
        "expected_team_count": 18,
        "min_merged_team_count": 16,
        "min_team_stats_coverage_count": 16,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=34, sofascore_season_id=37167, understat_league="Ligue_1", understat_season_year="2021"),
            _season_row("2022-23", sofascore_unique_tournament_id=34, sofascore_season_id=42273, understat_league="Ligue_1", understat_season_year="2022"),
            _season_row("2023-24", sofascore_unique_tournament_id=34, sofascore_season_id=52571, understat_league="Ligue_1", understat_season_year="2023"),
            _season_row("2024-25", sofascore_unique_tournament_id=34, sofascore_season_id=61736, understat_league="Ligue_1", understat_season_year="2024"),
            _season_row("2025-26", sofascore_unique_tournament_id=34, sofascore_season_id=77356, understat_league="Ligue_1", understat_season_year="2025", refresh_enabled=True),
        ],
    },
    {
        "code": "POR1",
        "name": "Liga Portugal",
        "country": "Portugal",
        "player_data_mode": PlayerDataMode.SOFASCORE_ONLY,
        "has_understat": False,
        "has_sofascore": True,
        "expected_team_count": 18,
        "min_merged_team_count": 16,
        "min_team_stats_coverage_count": 16,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=238, sofascore_season_id=37358),
            _season_row("2022-23", sofascore_unique_tournament_id=238, sofascore_season_id=42655),
            _season_row("2023-24", sofascore_unique_tournament_id=238, sofascore_season_id=52769),
            _season_row("2024-25", sofascore_unique_tournament_id=238, sofascore_season_id=63670),
            _season_row("2025-26", sofascore_unique_tournament_id=238, sofascore_season_id=77806, refresh_enabled=True),
        ],
    },
    {
        "code": "NED1",
        "name": "Eredivisie",
        "country": "Netherlands",
        "player_data_mode": PlayerDataMode.SOFASCORE_ONLY,
        "has_understat": False,
        "has_sofascore": True,
        "expected_team_count": 18,
        "min_merged_team_count": 16,
        "min_team_stats_coverage_count": 16,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=37, sofascore_season_id=36890),
            _season_row("2022-23", sofascore_unique_tournament_id=37, sofascore_season_id=42256),
            _season_row("2023-24", sofascore_unique_tournament_id=37, sofascore_season_id=52554),
            _season_row("2024-25", sofascore_unique_tournament_id=37, sofascore_season_id=61666),
            _season_row("2025-26", sofascore_unique_tournament_id=37, sofascore_season_id=77012, refresh_enabled=True),
        ],
    },
    {
        "code": "BEL1",
        "name": "Jupiler Pro League",
        "country": "Belgium",
        "player_data_mode": PlayerDataMode.SOFASCORE_ONLY,
        "has_understat": False,
        "has_sofascore": True,
        "expected_team_count": 16,
        "min_merged_team_count": 14,
        "min_team_stats_coverage_count": 14,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=38, sofascore_season_id=36894),
            _season_row("2022-23", sofascore_unique_tournament_id=38, sofascore_season_id=42404),
            _season_row("2023-24", sofascore_unique_tournament_id=38, sofascore_season_id=52383),
            _season_row("2024-25", sofascore_unique_tournament_id=38, sofascore_season_id=61459),
            _season_row("2025-26", sofascore_unique_tournament_id=38, sofascore_season_id=77040, refresh_enabled=True),
        ],
    },
    {
        "code": "SCO1",
        "name": "Scottish Premiership",
        "country": "Scotland",
        "player_data_mode": PlayerDataMode.SOFASCORE_ONLY,
        "has_understat": False,
        "has_sofascore": True,
        "expected_team_count": 12,
        "min_merged_team_count": 10,
        "min_team_stats_coverage_count": 10,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=36, sofascore_season_id=37029),
            _season_row("2022-23", sofascore_unique_tournament_id=36, sofascore_season_id=41957),
            _season_row("2023-24", sofascore_unique_tournament_id=36, sofascore_season_id=52588),
            _season_row("2024-25", sofascore_unique_tournament_id=36, sofascore_season_id=62408),
            _season_row("2025-26", sofascore_unique_tournament_id=36, sofascore_season_id=77128, refresh_enabled=True),
        ],
    },
    {
        "code": "ENG2",
        "name": "Championship",
        "country": "England",
        "player_data_mode": PlayerDataMode.SOFASCORE_ONLY,
        "has_understat": False,
        "has_sofascore": True,
        "expected_team_count": 24,
        "min_merged_team_count": 22,
        "min_team_stats_coverage_count": 22,
        "seasons": [
            _season_row("2021-22", sofascore_unique_tournament_id=18, sofascore_season_id=37154),
            _season_row("2022-23", sofascore_unique_tournament_id=18, sofascore_season_id=42401),
            _season_row("2023-24", sofascore_unique_tournament_id=18, sofascore_season_id=52367),
            _season_row("2024-25", sofascore_unique_tournament_id=18, sofascore_season_id=61961),
            _season_row("2025-26", sofascore_unique_tournament_id=18, sofascore_season_id=77347, refresh_enabled=True),
        ],
    },
]
