"""Team season public API: stat field lists, rank cohorts, and meta for sections."""

from __future__ import annotations

from typing import Literal

# All MergedTeamSeason scalar stat fields exposed under `stats` (excludes FKs / bookkeeping).
MERGED_TEAM_SEASON_STAT_FIELDS: tuple[str, ...] = (
    "matches",
    "rank",
    "points",
    "wins",
    "draws",
    "losses",
    "goals_for",
    "goals_against",
    "goal_difference",
    "average_ball_possession",
    "clean_sheets",
    "own_goals",
    "shots",
    "shots_on_target",
    "shots_off_target",
    "shots_against",
    "shots_on_target_against",
    "shots_from_inside_the_box",
    "shots_from_inside_the_box_against",
    "shots_from_outside_the_box",
    "shots_from_outside_the_box_against",
    "big_chances",
    "big_chances_against",
    "big_chances_created",
    "big_chances_created_against",
    "big_chances_missed",
    "expected_goals",
    "expected_assists",
    "corners",
    "corners_against",
    "accurate_passes",
    "accurate_passes_against",
    "total_passes",
    "accurate_passes_percentage",
    "accurate_long_balls",
    "total_long_balls",
    "accurate_long_balls_percentage",
    "accurate_crosses",
    "total_crosses",
    "accurate_crosses_percentage",
    "ball_recovery",
    "possession_lost",
    "tackles",
    "tackles_against",
    "interceptions",
    "interceptions_against",
    "clearances",
    "clearances_against",
    "saves",
    "duels_won",
    "duels_won_percentage",
    "aerial_duels_won",
    "aerial_duels_won_percentage",
    "ground_duels_won",
    "ground_duels_won_percentage",
    "successful_dribbles",
    "fouls",
    "yellow_cards",
    "red_cards",
    "yellow_cards_against",
    "red_cards_against",
    "offsides",
    "offsides_against",
    "penalties_taken",
    "penalty_goals",
    "penalty_goals_conceded",
    "goals_from_inside_the_box",
    "goals_from_outside_the_box",
    "headed_goals",
    "hit_woodwork",
)

StatDirection = Literal["higher", "lower"]

# Per-field direction for competition ranking (1 = best in league for that stat).
TEAM_STAT_DIRECTION: dict[str, StatDirection] = {f: "higher" for f in MERGED_TEAM_SEASON_STAT_FIELDS}

_LOWER_IS_BETTER = (
    "rank",
    "losses",
    "goals_against",
    "shots_against",
    "shots_on_target_against",
    "shots_from_inside_the_box_against",
    "shots_from_outside_the_box_against",
    "big_chances_against",
    "big_chances_created_against",
    "corners_against",
    "accurate_passes_against",
    "possession_lost",
    "tackles_against",
    "interceptions_against",
    "clearances_against",
    "yellow_cards_against",
    "red_cards_against",
    "offsides_against",
    "penalty_goals_conceded",
    "own_goals",
    "big_chances_missed",
    "fouls",
    "yellow_cards",
    "red_cards",
    "offsides",
)
for _f in _LOWER_IS_BETTER:
    TEAM_STAT_DIRECTION[_f] = "lower"

# Section groupings for `meta` + `sections` (aligned with HUD stat blocks).
TEAM_STAT_GROUPS: dict[str, str] = {
    "table": "Table",
    "shooting": "Shooting",
    "chances_set_pieces": "Chances & set pieces",
    "passing": "Passing",
    "possession": "Possession & duels",
    "defending": "Defending",
    "discipline": "Discipline",
}

TEAM_STAT_LABELS: dict[str, str] = {
    "matches": "Matches played",
    "rank": "League position",
    "points": "Points",
    "wins": "Wins",
    "draws": "Draws",
    "losses": "Losses",
    "goals_for": "Goals for",
    "goals_against": "Goals against",
    "goal_difference": "Goal difference",
    "average_ball_possession": "Avg. possession %",
    "clean_sheets": "Clean sheets",
    "own_goals": "Own goals",
    "shots": "Shots",
    "shots_on_target": "Shots on target",
    "shots_off_target": "Shots off target",
    "shots_against": "Shots against",
    "shots_on_target_against": "Shots on target against",
    "shots_from_inside_the_box": "Shots from inside box",
    "shots_from_inside_the_box_against": "Shots inside box against",
    "shots_from_outside_the_box": "Shots from outside box",
    "shots_from_outside_the_box_against": "Shots outside box against",
    "big_chances": "Big chances",
    "big_chances_against": "Big chances against",
    "big_chances_created": "Big chances created",
    "big_chances_created_against": "Big chances created against",
    "big_chances_missed": "Big chances missed",
    "expected_goals": "xG",
    "expected_assists": "xA",
    "corners": "Corners for",
    "corners_against": "Corners against",
    "accurate_passes": "Accurate passes",
    "accurate_passes_against": "Accurate passes against",
    "total_passes": "Total passes",
    "accurate_passes_percentage": "Pass accuracy %",
    "accurate_long_balls": "Accurate long balls",
    "total_long_balls": "Total long balls",
    "accurate_long_balls_percentage": "Long ball accuracy %",
    "accurate_crosses": "Accurate crosses",
    "total_crosses": "Total crosses",
    "accurate_crosses_percentage": "Cross accuracy %",
    "ball_recovery": "Ball recoveries",
    "possession_lost": "Possession lost",
    "tackles": "Tackles",
    "tackles_against": "Tackles against",
    "interceptions": "Interceptions",
    "interceptions_against": "Interceptions against",
    "clearances": "Clearances",
    "clearances_against": "Clearances against",
    "saves": "Saves",
    "duels_won": "Duels won",
    "duels_won_percentage": "Duels won %",
    "aerial_duels_won": "Aerial duels won",
    "aerial_duels_won_percentage": "Aerial duels won %",
    "ground_duels_won": "Ground duels won",
    "ground_duels_won_percentage": "Ground duels won %",
    "successful_dribbles": "Successful dribbles",
    "fouls": "Fouls",
    "yellow_cards": "Yellow cards",
    "red_cards": "Red cards",
    "yellow_cards_against": "Yellow cards against",
    "red_cards_against": "Red cards against",
    "offsides": "Offsides",
    "offsides_against": "Offsides against",
    "penalties_taken": "Penalties taken",
    "penalty_goals": "Penalty goals",
    "penalty_goals_conceded": "Penalties conceded",
    "goals_from_inside_the_box": "Goals from inside box",
    "goals_from_outside_the_box": "Goals from outside box",
    "headed_goals": "Headed goals",
    "hit_woodwork": "Hit woodwork",
}

TEAM_STAT_GROUP_FOR_KEY: dict[str, str] = {
    "matches": "table",
    "rank": "table",
    "points": "table",
    "wins": "table",
    "draws": "table",
    "losses": "table",
    "goals_for": "table",
    "goals_against": "table",
    "goal_difference": "table",
    "shots": "shooting",
    "shots_on_target": "shooting",
    "shots_off_target": "shooting",
    "shots_against": "shooting",
    "shots_on_target_against": "shooting",
    "shots_from_inside_the_box": "shooting",
    "shots_from_inside_the_box_against": "shooting",
    "shots_from_outside_the_box": "shooting",
    "shots_from_outside_the_box_against": "shooting",
    "goals_from_inside_the_box": "shooting",
    "goals_from_outside_the_box": "shooting",
    "headed_goals": "shooting",
    "hit_woodwork": "shooting",
    "big_chances": "chances_set_pieces",
    "big_chances_against": "chances_set_pieces",
    "big_chances_created": "chances_set_pieces",
    "big_chances_created_against": "chances_set_pieces",
    "big_chances_missed": "chances_set_pieces",
    "expected_goals": "chances_set_pieces",
    "expected_assists": "chances_set_pieces",
    "accurate_passes": "passing",
    "accurate_passes_against": "passing",
    "total_passes": "passing",
    "accurate_passes_percentage": "passing",
    "accurate_long_balls": "passing",
    "total_long_balls": "passing",
    "accurate_long_balls_percentage": "passing",
    "accurate_crosses": "passing",
    "total_crosses": "passing",
    "accurate_crosses_percentage": "passing",
    "average_ball_possession": "possession",
    "ball_recovery": "possession",
    "possession_lost": "possession",
    "duels_won": "possession",
    "duels_won_percentage": "possession",
    "aerial_duels_won": "possession",
    "aerial_duels_won_percentage": "possession",
    "ground_duels_won": "possession",
    "ground_duels_won_percentage": "possession",
    "successful_dribbles": "possession",
    "clean_sheets": "defending",
    "tackles": "defending",
    "tackles_against": "defending",
    "interceptions": "defending",
    "interceptions_against": "defending",
    "clearances": "defending",
    "clearances_against": "defending",
    "saves": "defending",
    "own_goals": "defending",
    "fouls": "discipline",
    "yellow_cards": "discipline",
    "red_cards": "discipline",
    "yellow_cards_against": "discipline",
    "red_cards_against": "discipline",
    "offsides": "discipline",
    "offsides_against": "discipline",
    "penalties_taken": "chances_set_pieces",
    "penalty_goals": "chances_set_pieces",
    "penalty_goals_conceded": "chances_set_pieces",
    "corners": "chances_set_pieces",
    "corners_against": "chances_set_pieces",
}


def team_meta_payload() -> dict:
    stat_defs = {}
    for key in MERGED_TEAM_SEASON_STAT_FIELDS:
        stat_defs[key] = {
            "label": TEAM_STAT_LABELS.get(key, key),
            "group": TEAM_STAT_GROUP_FOR_KEY.get(key, "table"),
        }
    return {
        "stat_groups": TEAM_STAT_GROUPS,
        "stats": stat_defs,
        "ranked_keys": list(MERGED_TEAM_SEASON_STAT_FIELDS),
    }


def team_sections_for_row(
    row,
    ranks_season: dict[str, int | None],
    ranks_per_match: dict[str, int | None],
    stat_values: dict[str, object],
) -> dict[str, dict]:
    """Grouped metrics with season + per-match league ranks (`stat_values` = display numbers)."""
    sections: dict[str, dict] = {}
    for group_key, group_label in TEAM_STAT_GROUPS.items():
        entries = []
        for stat_key in MERGED_TEAM_SEASON_STAT_FIELDS:
            if TEAM_STAT_GROUP_FOR_KEY.get(stat_key) != group_key:
                continue
            entries.append(
                {
                    "key": stat_key,
                    "label": TEAM_STAT_LABELS.get(stat_key, stat_key),
                    "value": stat_values.get(stat_key, getattr(row, stat_key)),
                    "rank": ranks_season.get(stat_key),
                    "rank_per_match": ranks_per_match.get(stat_key),
                }
            )
        sections[group_key] = {
            "label": group_label,
            "metrics": entries,
        }
    return sections
